fix: se agrega estilos boton radio
gcba/Obelisco pull request #101
Opened 2022-10-27 14:26 UTC by davisLjr

2022-10-31 18:06 UTC, Jesus1397 commented on src/components/Form/Radio.stories.tsx
> +          <input type="radio" name="options1" id="option1" className="btn-check" checked></input>
Corregir el checked en la posicion donde esta el elemento con la clase active

2022-10-31 20:29 UTC, alan199912 commented on src/scss/components/_form.scss
> +    background-color: $blue;
Agregar:

```
box-shadow: none;
text-decoration: none;
```

Porque cada vez que haces click en un boton con estado activo se visualiza el subrayado

2022-10-31 20:30 UTC, alan199912 commented on src/scss/components/_form.scss
> +    background-color: $blue;
Agregar `btn-check` como hijo de `btn-chip`.

Estoy con dudas si `&:active, &:checked + .btn-chip` dentro de `.btn-check` funciona o si tiene funcionamiento

2022-10-31 20:54 UTC, davisLjr commented on src/components/Form/Radio.stories.tsx
> +          <input type="radio" name="options1" id="option1" className="btn-check" checked></input>
solucionado

2022-10-31 20:54 UTC, davisLjr commented on src/scss/components/_form.scss
> +    background-color: $blue;
solucionado

2022-11-01 13:40 UTC, alan199912 requested changes
Tengo duda con lo del `text-decoration` porque en el componente de `button checkbox` lo tiene, enonces lo dejamos o lo sacamos? @lautarorodriguez96

2022-11-01 13:40 UTC, alan199912 commented on src/scss/components/_form.scss
>      background-color: $blue;
Esta bien, solo borra el comentario y agrega un `enter` para darle un espacio al `&:hover`

2022-11-01 13:45 UTC, lautarorodriguez96 commented on src/scss/components/_form.scss
>      background-color: $blue;
Lo consulto, porque en el ui kit no está. 
También veo que tiene un span dentro del label y clases en el contenedor del componente. Habría que igualar lo mas posible la sintaxis entre los componentes button checkbox y  button radio

2022-11-02 13:31 UTC, lautarorodriguez96 approved these changes

2022-11-02 13:46 UTC, alan199912 approved these changes

2022-11-02 16:18 UTC, merged