fix: solucion active y hover de opciones
gcba/Obelisco pull request #102
Opened 2022-10-27 17:21 UTC by davisLjr

2022-10-31 20:44 UTC, alan199912 requested changes

2022-10-31 20:44 UTC, alan199912 commented on src/scss/components/_options.scss
> +      &:active {
No entiendo el cambio de.

`btn-dropdown` No tiene `active` sino `show`

2022-10-31 20:44 UTC, alan199912 commented on src/scss/components/_options.scss
> +      &.active {
No hace falta agregar `.active` por fuera.

Para obtener una mejor lectura del codgo los podes combinar agregando una coma

```
&:active, &.active {}
```
El carácter de coma básicamente actúa como la palabra "y" dentro del selector

2022-10-31 21:02 UTC, davisLjr commented on src/scss/components/_options.scss
> +      &:active {
solucionado

2022-10-31 21:02 UTC, davisLjr commented on src/scss/components/_options.scss
> +      &.active {
solucionado

2022-10-31 21:14 UTC, alan199912 commented on src/scss/components/_options.scss
> +      &:active {
Para ese caso debes agregar dentro de `.btn-dropdown` agregar debajo de todo

```
&:active {
  color:$grisulado-900;

  &.dropdown-toggle:after {
    content: $icon-chevron-up;
  }
}
```

2022-11-01 14:33 UTC, alan199912 requested changes
Encontre que pasa lo mismo pero cuando ya esta activo, es decir, las letras se ponen de color negro.

Para solucionar esto proba con lo siguiente:

```
&:active {
          &[aria-expanded="false"] {
            color: $grisulado-900;
  
            &.dropdown-toggle:after {
              content: $icon-chevron-up;
            }
          }

          &[aria-expanded="true"] {
            color: $white;
  
            &.dropdown-toggle:after {
              content: $icon-chevron-up-white;
            }
          }
        }
```

Ahi tomamos como referencia el ara-expanded , cuando esta activo lo pone de color blanco y cuando esta en false lo pone de grisulado.


Acordate tambien de formatear el codigo con `Prettier`

2022-11-01 15:27 UTC, alan199912 approved these changes

2023-01-30 19:01 UTC, closed without merging