fix: se modifica ancho de componente audio
gcba/Obelisco pull request #106
Opened 2022-11-02 14:02 UTC by victorianastasi

2022-11-02 14:31 UTC, alan199912 requested changes
Remover el `<div>` que tiene de mas
![image](https://user-images.githubusercontent.com/40763553/199516647-bf8b67af-7c29-4ff2-83ed-c8767188e667.png)

2022-11-02 14:31 UTC, alan199912 commented on src/scss/components/_audio.scss
> +  max-width: 340px;
No se si les pondria un maximo, porque si se encuentra en una tarjeta grande se va a ver chico.

2022-11-02 14:50 UTC, victorianastasi commented on src/scss/components/_audio.scss
> +  max-width: 340px;
Si, es verdad, se veria chico. En el XD tiene 340px cuando no esta dentro de una tarjeta, pero se podria preguntar
![XD_audio](https://user-images.githubusercontent.com/60082396/199520906-43ca2369-d5f8-4f1b-814c-a5b107cd0dd4.png)

2023-01-09 14:39 UTC, matilope commented on src/components/Audio/Audio.stories.scss
> +.cards-container, .audio-container, .accordion-wrapper, .horizontal-container {
Si no me equivoco, estas clases .accordion-wrapper y .horizontal-container estan de más

2023-01-09 14:39 UTC, matilope commented on src/components/Audio/Audio.stories.scss
> +.horizontal-container {
Acá lo mismo, si no me equivoco, estaría de más esta clase

2023-01-17 17:39 UTC, lautarorodriguez96 approved these changes

2023-01-17 17:41 UTC, alan199912 approved these changes

2023-01-17 17:44 UTC, davisLjr approved these changes

2023-01-17 17:45 UTC, merged