feat: creacion de componente spinner
gcba/Obelisco pull request #108
Opened 2022-11-04 13:54 UTC by matilope

Se creo el componente spinner con texto y sin texto
https://xd.adobe.com/view/4177d82c-6f12-414e-88ac-d930298974bd-1424/

2022-11-04 16:01 UTC, alan199912 requested changes
No hace falta crear 2 archivos `*/**.stories.tsx`, podes declarar los componentes en un solo archivo.

---

Tambien mostraria los colores que se pueden meter en un spinner, ahi deberias hacer un componente de React para que mediante `props` agregar el tipo de color. 
@lautarorodriguez96 solo se va a utilizar el color azul como `spinner` ?

2022-11-04 17:42 UTC, matilope commented on src/scss/components/_spinner.scss
> +    width: $spinner-width;
Bueno, ya hice todos los cambios que se me pidieron, el único color que saque fue el de warning que es el que usan como primary, después puse todos los demás e hice las correcciones, cuando se confirme lo del color lo vuelvo a subir.

2022-11-17 20:00 UTC, lautarorodriguez96 approved these changes

2022-11-18 19:37 UTC, alan199912 approved these changes

2022-11-22 13:52 UTC, merged