feat: se agrega el componente Botones con bordes
gcba/Obelisco pull request #111
Opened 2022-12-07 17:16 UTC by victorianastasi

fix: se modifica font-weight de btn-lg

2022-12-07 17:47 UTC, matilope commented on src/scss/components/_button.scss
> +$btn-font-weight-lg: 700;
hay una variable que tiene el font-weight de 700 que es $font-weight-bold

2022-12-07 18:26 UTC, alan199912 requested changes

2022-12-07 18:26 UTC, alan199912 commented on src/scss/components/_button.scss
> +  .btn-outline-#{$color}{
Para hacer un codigo mas prolijo y no repetir algunas propiedades que comparten tanto `.btn-#{color}` & `.btn-outline-#{}`

Podrias declararlo de la siguiente manera:

```
.btn-#{$color}, .btn-outline-#{$color} {
   // aca adentro irian las cosas que comparten
}
```
Eso si, las cosas que no comparten dejarlos por separado.

2023-01-10 13:36 UTC, lautarorodriguez96 commented on src/components/Button/Button.stories.tsx
> +export const ConIconos = (): JSX.Element => {
Al cambiar el tamaño de los botones, el enlace de descarga no está alineado el icono. Habria que reemplazar el vertical-align: top/sub

2023-01-10 13:38 UTC, lautarorodriguez96 commented on src/components/Button/Button.stories.scss
> +  max-width: 360px;
Este css no va a impactar despues en el componente.

2023-01-10 19:01 UTC, alan199912 requested changes

2023-01-11 14:09 UTC, alan199912 requested changes
Cuando haces focus en los botones chicos es como que se levanta y en los grandes baja a los demas

2023-01-11 14:26 UTC, lautarorodriguez96 commented on src/components/Button/ContainerButton.stories.tsx
> +export const ConEnlace = (): JSX.Element => {
Al hacer click en el boton de enlace queda en azul el texto

2023-01-11 14:45 UTC, matilope commented
- Cuando se clickea el botón se mueve para arriba, no se si es un comportamiento que debería pasar ( es que cuando esta focus, la clase btn tiene un margin-bottom: 1rem ).

- En los botones con icono pienso yo para centrar el contenido (icono y texto) se le puede agregar dos clases a ese boton: d-flex y align-items-center y lo mismo de agregar esas clases al contenedor, junto con el btn-wrapper y para que no afecte al resto de botones que tambien usa la clase de btn-wrapper, tipo de esta forma en el codigo:
![image](https://user-images.githubusercontent.com/66441937/211834668-f3c427ad-4561-4f37-964b-c2fcb081e3fb.png)

Y así seria la vista:

![image](https://user-images.githubusercontent.com/66441937/211835799-406afe9e-0d17-4bd1-8ae8-ead4fa5d74e0.png)


De todas formas evaluen la diferencia me parece que asi deberia ser pero por las dudas fijense que les parece el cambio o si queda bien centrado de esa forma.

2023-01-11 20:06 UTC, alan199912 requested changes

2023-01-11 20:09 UTC, alan199912 requested changes

2023-01-11 20:09 UTC, alan199912 commented on src/scss/components/_button.scss
> +    @include hover(){
Por que esto? tengo entendido que ya el color es blanco cuando esta en hover

2023-01-11 20:09 UTC, alan199912 commented on src/scss/components/_button.scss
> +      margin-right: 7px;
Pasar estos ` 7px` a rem

2023-01-11 20:15 UTC, matilope commented on src/scss/components/_button.scss
> +  justify-content: center;
el justify-content: center; me parece que esta de más

2023-01-12 14:19 UTC, alan199912 requested changes

2023-01-12 14:19 UTC, alan199912 commented on src/scss/components/_button.scss
> +.btn-link, .btn-outline-link {
Para no declarar la clase de esta manera, tanto `btn-link` & `btn-outline-link`, seria mejor y mas prolijo agregar una array dentro de **theme-colors** que incluya el color link.
Ahora teniendo eso, en el for donde estamos reccorriendo todos los colores, debemos usar el condicional if para modificar la clase link.
Tanto en `btn-#{color}` como `btn-outline-#{color}`

2023-01-12 14:27 UTC, alan199912 commented on src/scss/components/_button.scss
> +.btn-link, .btn-outline-link {
```
$theme-colors: map-merge(
  $theme-colors,
  (
    'link': $ghost
  )
);
```

2023-01-17 15:34 UTC, lautarorodriguez96 approved these changes

2023-01-17 15:35 UTC, merged