perf: se saco anysort para mejorar performance, cambios en manager ts
gcba/Obelisco pull request #124
Opened 2023-02-10 12:48 UTC by matilope

Cambios que hice:
- Saque la libreria de anysort, se encontro una manera de ordernarlos sin depender de esa libreria. ademas esta libreria tenia dos dependencias y esas dependencias tenian otras dependencias mas y bueno.
- En manager.ts el brand url estaba mal escrito porque la url del storybook empieza en mayuscula (Obelisco) y antes estaba escrito obelisco. Esto lo pueden probar yendo a la url y apretando en el icono de arriba a la izquierda. Tambien si se paran encima del icono sin apretarlo van a ver que dice algo de "Me van a cambiar, no te preocupes", bueno eso era el brandTitle, que tambien ahora lo cambie a Obelisco, lo unico que no pude hacer que quiza es por la version de obelisco es agregar el brandTarget: '_self' para que cuando se aprete en obelisco te recarge la pagina en vez de mandarte a la misma pagina en otra pestaña.
- Cambie el titulo de botones en caja porque el "En Caja" estaba justamente en mayuscula y se ve que es algo que me quedo colgado a mi y esta mal porque como los demas deberia ser por ej: "En caja"
- En el get-started marca un problema de accesibilidad por el orden de los headers, este problema se da porque en el get-started hay un h1 y luego le sigue un h3 creando ese desorden, yo lo que hice fue cambiar ese h3 por un h2 (yo quiza le pondria un span en realidad) y luego editar el scss de la historia y ponerle el font-size de un h3 para que quede de la misma forma.

2023-02-10 14:15 UTC, alan199912 requested changes

2023-02-10 14:15 UTC, alan199912 commented on src/get-started/GetStarted.stories.scss
> +    h2{
Prodrias usar **h2:first-of-type**

2023-02-10 14:15 UTC, alan199912 commented on package.json
> +    "@gcba/obelisco": "^1.13.0"
Este lo podriamos quitar, ya que no tiene sentido que tengamos como dependencia obelisco.

2023-02-10 18:04 UTC, alan199912 requested changes
Audio con contenedor tambien esta con mayusculas. Lo mismo con tipografia en texto secundario y lista ordenada

2023-02-10 18:43 UTC, alan199912 approved these changes

2023-02-13 18:14 UTC, lautarorodriguez96 approved these changes

2023-02-14 21:43 UTC, lautarorodriguez96 approved these changes

2023-02-14 22:07 UTC, merged