Feat list
gcba/Obelisco pull request #126
Opened 2023-02-13 19:14 UTC by davisLjr

Se agregaron los componentes Listas.
Listo para que se les haga revisiones para mejoras, el martes14/02 se haran deifiniciones sobre los mismos que puede afectar la estructura o la manera de implementacion de los componentes para que sean mas generales.

2023-02-13 20:26 UTC, matilope commented on src/components/List/ListSpecialties.stories.tsx
> +            <label className="custom-control-label" htmlFor="profession-content"></label>
Hay que centrar el del after no? aunque se arregla con el fix de la version 1.46.1, cierto?

2023-02-13 20:26 UTC, matilope commented on src/components/List/ListSpecialties.stories.tsx
> +    'Item lorem ipsum dolor sit',
Habría que ver que poner para evitar usar lorem

2023-02-13 20:48 UTC, davisLjr commented on src/components/List/ListSpecialties.stories.tsx
> +            <label className="custom-control-label" htmlFor="profession-content"></label>
El after?, me das mas detalles porfa

2023-02-13 20:50 UTC, davisLjr commented on src/components/List/ListSpecialties.stories.tsx
> +    'Item lorem ipsum dolor sit',
Si, en el diseño tambien falta el texto.
Esto seguramente se defina con diseño.

2023-02-13 20:55 UTC, matilope commented on src/components/List/ListSpecialties.stories.tsx
> +            <label className="custom-control-label" htmlFor="profession-content"></label>
lo del radio viste que no queda centrado? pero eso lo habian arreglado en el fix de 1.46.1 pero no esta subido todavia.

2023-02-13 21:15 UTC, alan199912 requested changes
Deja anclado el link a figma 🙏

2023-02-13 21:15 UTC, alan199912 commented on src/components/List/ListSpecialties.stories.tsx
> +  const exponent = (value % 1).toFixed(2).substr(2);
En lugar de `substr` utiliza `splice`. (substr marca como deprecado)

2023-02-13 21:15 UTC, alan199912 commented on src/components/List/ListSpecialties.stories.tsx
> +PaymentStatusDisplay.propTypes = {
No es necesario declarar `PaymentStatusDisplay.propTypes` dos veces, ya que cada vez que lo declaras estás sobrescribiendo.

2023-02-14 12:51 UTC, davisLjr commented on src/components/List/ListSpecialties.stories.tsx
> +PaymentStatusDisplay.propTypes = {
perfecto ahi lo cambio

2023-02-14 12:51 UTC, davisLjr commented on src/components/List/ListSpecialties.stories.tsx
> +  const exponent = (value % 1).toFixed(2).substr(2);
Perfecto ahi lo cambio

2023-02-14 12:52 UTC, davisLjr commented on src/components/List/ListSpecialties.stories.tsx
> +  const exponent = (value % 1).toFixed(2).substr(2);
El link a figma lo deje anclado en el PR

2023-02-14 14:03 UTC, alan199912 requested changes

2023-02-14 14:03 UTC, alan199912 commented on src/scss/components/_list.scss
> +  padding: $list-header-padding 0;
En el componente `Metodo de pago`, tiene que ser 1rem.
Fijate porque creo que se usa en otros lados tambien

2023-02-14 15:39 UTC, davisLjr commented on src/components/List/ListSpecialties.stories.tsx
> +            Puntaje de scoring: <span>{scoring} puntos</span>
Muy buena pregunta, esto se consultara hoy con equipo de diseño.

2023-02-14 15:46 UTC, davisLjr commented on src/components/List/ListSpecialties.stories.tsx
> +            Pagar Boleto(BUI)
Dale, perfecto.

2023-02-14 15:46 UTC, davisLjr commented on src/scss/components/_list.scss
> +  padding: $list-header-padding 0;
Dale, perfecto

2023-02-17 19:51 UTC, alan199912 requested changes

2023-02-17 19:51 UTC, alan199912 commented on src/scss/components/_list.scss
> +    margin-bottom: $list-informative-margin;
Podes utilizar el primer `li` y dentro utilizar `&:last-child`, `&:has(i)` y asi con los demas, para que esten todos juntos y no por separado

2023-02-22 12:58 UTC, alan199912 requested changes
Lista informativa esta bien, los demas componentes van a quedar??

2023-02-22 12:58 UTC, alan199912 commented on src/scss/components/_list.scss
> +@mixin list-informative-style($position-left, $icon-margin-right) {
Este mixin debe ir debajo de las variables.

Podes tomar como referencia el archivo `_example.scss`

2023-02-22 13:17 UTC, Jesus1397 commented on src/scss/components/_list.scss
> +@mixin list-informative-style($position-left, $icon-margin-right) {
Genial, sobre los demas componentes no se en un rato tenemos reu con Lauti y te confirmo

2023-03-06 19:36 UTC, closed without merging