fix: se crearon los accesos nuevos segun ficha y ui kit
gcba/Obelisco pull request #134
Opened 2023-03-01 15:22 UTC by matilope

Se crearon los accesos nuevos según ficha y UI KIT.

Ficha: https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/Fichas?node-id=1%3A534&t=P1arWNkBMpQVT2gh-0

UI KIT: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?node-id=956%3A8493&t=7tw9w08Q4j4SOyoA-0

https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/UI-KIT---Obelisco?node-id=958%3A8488&t=7tw9w08Q4j4SOyoA-0

Lista de accesos se puede ver en la ficha y aquí: https://github.com/gcba/estandares/issues/226

* No incluye el sin borde porque se usa para organismos y ponerlo en componente puede generar confusion

Se arreglaron paddings, margins, se agrego la clase active y el estado (pseudo clase) active, los paddings en mobile, tamaños de los iconos, tipo de iconos, las nuevas variaciones de los componentes, nuevo componente con icono, titulo (span) y parrafo.

2023-03-13 15:30 UTC, Jesus1397 commented on src/components/List-group/Access.stories.tsx
> +        <i className="bx bxs-info-circle align-self-center"></i>
Cuando usas un icono de Material, no toma el espaciado, ademas le sacaria el align-self-center y haria que lo aplique a iconos de tipo <i> y <span>

2023-03-20 18:47 UTC, matilope commented
Arreglos en el ultimo commit: 
* Aunque en el UI KIT aparezca en accesos (organismos) con dos iconos en el card-access-body, esto era solo para mostrar que puede haber dos iconos uno a la izquierda y otro a la derecha.
Deje el acceso simple sin la clase reverse y los de "Con lista de accesos" y "Con categorías" están con la clase reverse para que se sepa de su posible uso.
* También a esta clase de "reverse" se le agrego el justify-content: space-between; para que no quede el titulo y párrafo pegados a la derecha.

2023-03-21 13:40 UTC, alan199912 requested changes
Por que en los ejemplos esta en el tamaño **sm**??

2023-03-21 13:40 UTC, alan199912 commented on src/scss/components/_list-group.scss
> +    padding: 0.75rem 1.5rem;
El padding no es el mismo.
En el figma tiene 16px en `Y` y 44px en `X`

2023-03-28 20:55 UTC, matilope commented
Chequear paddings son diferentes en los organsimos

2023-03-30 15:18 UTC, matilope commented
la clase para sacar el box-shadow es: **no-shadow**  quiza habria que cambiarle el nombre y también nombrarlo en estándares

2023-03-30 15:25 UTC, alan199912 requested changes

2023-03-30 15:25 UTC, alan199912 commented on src/organisms/Access/AccessComplete.stories.tsx
> +  <div className="list-group-container">
Hacelo componente de React

2023-03-31 18:29 UTC, lautarorodriguez96 commented on .storybook/preview.ts
> +  'Organismos|Acceso/Lista de accesos',
La lista de accesos no la pondría dentro de organismos, lo dejaría dentro del componente accesos como la sección de tarjeta ya que para el uso se necesitan o no determinadas clases. Que opinan? @alan199912 @Jesus1397 @victorianastasi @davisLjr

2023-03-31 18:29 UTC, lautarorodriguez96 commented on src/organisms/Access/AccessList.stories.tsx
> +
Acá hay que aclarar en la ficha las clases que se usan para la vista vertical/horizontal y desde donde se deberia usar el componente (etiqueta html)

2023-03-31 18:33 UTC, matilope commented on src/organisms/Access/AccessList.stories.tsx
> +
Lauti aca te paso la nueva ficha se ve que hay varias o estan en distintas branches, ahora lo actualizo en el pr
https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/kt5sRWwgvzLgLqvx6uDZGU/Fichas?node-id=1-534&t=NDxgoKZZG02sPD0E-0

2023-03-31 19:27 UTC, Jesus1397 commented on src/components/List-group/index.tsx
> +export const AccesosBordeComponent: React.FC<AccessStateInterface> = (
Los nombres de los componentes estan en español e ingles, los demas componentes de storybook estan en ingles asi que lo cambiaria para seguir con la concordancia

2023-03-31 19:46 UTC, Jesus1397 commented on .storybook/preview.ts
> +  'Organismos|Acceso/Lista de accesos',
Creo que en este momento, no es necesario mover Accesos a organismos, ya que esto podria generar complicaciones, ya se esta usando como un componente, esto de crear organismos tendria que aplicarse a las cosas futuras y no a los que ya estan creados
Ademas se esta usando una hoja de css para un componente y organismo a la vez, se tendria que mover todo el "bloque" o si no, no hacerlo

2023-03-31 20:17 UTC, victorianastasi commented on .storybook/preview.ts
> +  'Organismos|Acceso/Lista de accesos',
Si, creo que seria mejor que este en componente accesos, tal vez se puede poner disposiciones en vez de listas de accesos, para que no genere confusion

2023-04-04 15:12 UTC, alan199912 requested changes
Fijate que en la separacion de acceso con categoria te quedo mas grande.
![image](https://user-images.githubusercontent.com/40763553/229837234-827850b7-f5cb-4006-b136-4472be1e2746.png)

2023-04-04 15:12 UTC, alan199912 commented on src/organisms/Access/index.tsx
> +import * as React from 'react';
Dejar solo el import React, porque sino va a traer todo lo de la libreria y solo necesitamos **React**

2023-04-04 15:12 UTC, alan199912 commented on src/scss/components/_list-group.scss
> +  .no-shadow {
Ya existe una clase de bootstrap llamada `shadow-none`

2023-04-04 15:14 UTC, matilope commented on src/scss/components/_list-group.scss
> +  .no-shadow {
Si, pero tiene el !important entonces cuando se hace hover, focus no cambiar el estado del componente

2023-04-04 15:26 UTC, alan199912 commented on src/scss/components/_list-group.scss
> +  .no-shadow {
Podrias utilizar esto:

```
&:not(:hover) {
    .card-item {
      @extend .shadow-none;
    }
  }
```
Tambien valida que sea para los comoponentes con categoria y lista porque sino se cambia en todos

2023-04-04 15:41 UTC, matilope commented on src/organisms/Access/index.tsx
> +import * as React from 'react';
Ok, funciona en esos dos pero no en el de simple porque en ese, por alguna razón, no se le saca el box-shadow. (asi esta planteado en el ui kit)

2023-04-04 17:39 UTC, matilope commented on src/scss/components/_list-group.scss
> +  .no-shadow {
Te habia comentado pero no se envio. Sirve en el de categorias y el de con lista de accesos pero no sirve en el simple, porque ahi si te fijas en el ui kit esta distinto a estos dos, o sea el box shadow lo tiene. Ademas se necesita poder agregar la clase que saque el shadow en los accesos normales pero que siga tambien funcionando sus distintos estados (hover, focus, etc)

2023-04-04 18:20 UTC, alan199912 commented on src/scss/components/_list-group.scss
> +  .no-shadow {
Proba con esto:

```
&:has(.container-access) {
    &:not(:hover) {
      .card-item {
        @extend .shadow-none;
      }
    }
  }
```

2023-04-11 13:32 UTC, alan199912 requested changes
En principio fijarse si la etiqueta `<span class="card-access-icon descriptive">Nº</span>` se puede reemplazar por un icono.

---

Como segundo lugar por cuestiones de semantica de HTML.
Tenemos que fijarnos que los `hr` tenga sentido semántico y ayude a organizar y estructurar el contenido de manera clara para los usuarios y para los motores de búsqueda.

Sin embargo, en este caso, la separación de los hr no parece estar totalmente coherente con la estructura de contenido. El primer hr no está claramente relacionado con el contenido que lo precede o sigue, y podría ser confuso para los usuarios. El segundo hr que se encuentra dentro de la clase "access-option" parece ser más apropiado para separar los diferentes elementos de acceso que se muestran allí.

Estructurar el contenido HTML para que los `hr` esten fuera de la etiqueta `div`

Ejemplo:

```
<hr className="clearfix mt-0" />
    <div className="container-access">
        // content
   </div>
<hr className="clearfix my-0 mt-2" />
```

2023-04-12 20:46 UTC, matilope commented
Falta la confirmación del margen inferior de un hr en lista de accesos.

2023-04-14 13:25 UTC, alan199912 requested changes

2023-04-14 13:25 UTC, alan199912 commented on src/organisms/Access/index.tsx
> +export const SimpleComponent = (): JSX.Element => {
La idea de hacerlo componente de React es para reutilizarlo en los demas.
Con esto solo estas haciendo componentes como estaba antes solo que esta separado en un index.

Esto se puede subir y lo podemos ver mas adelante.
No se que opinas @lautarorodriguez96 ?

2023-04-14 13:44 UTC, matilope commented on src/organisms/Access/index.tsx
> +export const SimpleComponent = (): JSX.Element => {
Ahora Vicky esta haciendo unos cambios en la branch, cuando los termine me pongo a hacer esto para que sea un solo componente que pueda reutilizarse en estos 3 ejemplos. No hay problema.

2023-04-14 15:03 UTC, lautarorodriguez96 commented on src/organisms/Access/index.tsx
> +export const SimpleComponent = (): JSX.Element => {
Si, para que quede todo como componente en react, seria lo mejor. 
En este caso si lleva mucho tiempo será mejora futura.

2023-04-14 17:37 UTC, victorianastasi commented
Tal vez en organismos podriamos sacar Acceso completo y dejar solo los 3 dentro de Accesos (simple, con lista de accesos y con categorias) porque ahora horizontal y vertical que estaban en Lista de accesos dentro de organismos paso a componentes

2023-04-14 17:55 UTC, alan199912 requested changes

2023-04-14 17:55 UTC, alan199912 commented on src/components/List-group/Access.stories.tsx
> +  name: 'Accesos con borde'
Tiene muy repetido la palabra Accesos en todos los nombres.
Deberia ser Con borde, Con Descripcion, etc.

2023-04-14 18:20 UTC, matilope commented on src/components/List-group/Access.stories.tsx
> +  name: 'Accesos con borde'
@lautarorodriguez96  en la ficha aparece como los puse, en caso de que se cambie avisen, alan me nombro esto porque por ejemplo en botones esta puesto de esa forma.

2023-04-14 18:28 UTC, victorianastasi commented on src/organisms/Access/index.tsx
> +              <h6 className="title-option">Categoría 1</h6>
si, es verdad, lo pusieron asi en figma, lo consultamos con nati

2023-04-17 13:22 UTC, alan199912 requested changes

2023-04-17 13:22 UTC, alan199912 commented on src/scss/components/_list-group.scss
> +        padding: 1rem;
El padding en Y tiene que ser de 22px, es decir, 1.375rem.

![image](https://user-images.githubusercontent.com/40763553/232496175-d0217880-2b8c-4019-a075-196f6f9e7156.png)

2023-04-17 13:22 UTC, alan199912 commented on src/scss/components/_list-group.scss
> +$padding-list-group-item-sm-mobile: 0.5rem 1rem;
Aca el padding en Y deberia ser de 12px, es decir, 0.75rem.

![image](https://user-images.githubusercontent.com/40763553/232496523-48be0cd1-d8f8-41bd-aa15-a5f55c4b92ea.png)

2023-04-17 17:31 UTC, matilope commented
Ahora con el margen del icono en 4px no se rompen los accesos en la pagina de Buenos Aires. Este margin lo pongo asi porque es como medí todos los paddings margenes de los elementos, en vez de pararme directo en el icono me paro en su contenedor, que es la manera correcta de hacerlo (hablando de figma).
![image](https://user-images.githubusercontent.com/66441937/232563876-67e64488-35dc-4bfe-b9b7-6103e293f446.png)

2023-04-18 20:54 UTC, victorianastasi commented
Luego de reunion con diseño: se modifico padding en access-option a 10px en accesos con categorias (en mobile 8px), se extendio la clase h5 en titulos de categorias, la distancia del icono en acceso grande de accesos organismos es 12px, icono al lado del titulo es de 32px

2023-04-20 14:22 UTC, victorianastasi commented
Diseño confirmo que el padding de hr en mobile en accesos organismos es 16px, en listas y categorias

2023-04-21 14:03 UTC, victorianastasi approved these changes

2023-04-21 17:32 UTC, davisLjr approved these changes

2023-04-21 17:37 UTC, Jesus1397 approved these changes

2023-04-21 18:49 UTC, alan199912 approved these changes

2023-04-24 13:54 UTC, merged