feat: tooltip
gcba/Obelisco pull request #137
Opened 2023-03-08 19:54 UTC by Jesus1397

Figma: 
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/9BNEtR6VWye73nPWPNgG4t/UI-KIT---Obelisco?node-id=2332-12566&t=EXxRZGbngwpQ35yb-0

- El ancho en desktop es 18rem y en mobile es de 10rem

Dejo la ficha de Estandares tambien:
https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/UomlJbV9f4cowU0JP3urLb/Fichas?node-id=188-812&t=NKHlh5rh7couodXt-0

pd: La forma en la que se muestra puede cambiar, mañana Diseño da la respuesta final

2023-03-09 13:41 UTC, alan199912 commented on src/scss/components/_tooltip.scss
> +[data-tooltip] {
Para hacer un poco mas el codigo mas legible, podrias implementar lo siguiente:

```
[data-tooltip] {
   &:before {
       // code
   }

   &:after {
       // code
   }
   
   &:[data-flow='bottom-left'] {
      // code
   }

}
```

Asi con los demas

2023-03-09 13:54 UTC, matilope commented on src/components/Tooltip/Tooltip.stories.scss
> +
Dale un format document asi te saca este espacio

2023-03-09 13:54 UTC, matilope commented on src/components/Tooltip/Tooltip.stories.scss
> +        display: flex;
Ya recibe el display: flex; del tooltip-column asi que no haria falta aca.

2023-03-09 13:54 UTC, matilope commented on src/components/Tooltip/Tooltip.stories.scss
> +        display: flex;
Ya recibe el display: flex; del tooltip-column asi que no haria falta aca.

2023-03-09 13:56 UTC, matilope commented on src/components/Tooltip/Tooltip.stories.tsx
> +Tooltip.story = {
Esto de momento esta demás porque el nombre que le pusiste es el mismo de la constante.
Si puede llegar a cambiar el nombre diría de dejarlo.

2023-03-09 13:59 UTC, alan199912 requested changes

2023-03-09 13:59 UTC, alan199912 commented on src/components/Tooltip/Tooltip.stories.tsx
> +        <span data-tooltip="Esta es la descripción de un tooltip" data-flow="top-right">
Porque el button esta envuelto en el span?
Se puede utilizar el `data-tooltip` directamente en el button

2023-03-09 13:59 UTC, alan199912 commented on src/components/Tooltip/Tooltip.stories.tsx
> +        <span data-tooltip="Esta es la descripción de un tooltip" data-flow="top-right">
Dato adicional: Podrias hacerlo un componente y reutilizarlo para que no te quede tando codigo

2023-03-09 14:11 UTC, alan199912 requested changes

2023-03-09 14:11 UTC, alan199912 commented on src/scss/components/_tooltip.scss
> +@mixin tooltipY($positionX, $positionY, $translateX, $translateY, $arrowX, $arrowValue) {
Por que nombras la variable `$arrowX` ? si los usas como si fueran de **Y**, como top o bottom.

2023-03-09 14:14 UTC, matilope commented on src/components/Tooltip/Tooltip.stories.scss
> +@include media-breakpoint-down(md) {
Sacaría el import de Obelisco y usaría
@media screen and (max-width: 975.98px) {
 // el código
}

2023-03-09 14:28 UTC, matilope commented on src/scss/components/_tooltip.scss
> +  &:before,
Quizá el mixin lo dejaria asi para que no se use esas propiedades extras en el before que aunque se terminan cancelando las del after estarian de mas

`
@mixin tooltipY($positionX, $positionY, $translateX, $translateY, $arrowX, $arrowValue) {

  //Box
  &:after {
    #{$positionX}: calc(50% - 8px);
    #{$positionY}: calc(100%);
    transform: translate($translateX, $translateY);
  }

  //Arrow
  &:before {
    transform: rotate($tooltip-arrow-rotate);
    background-color: $grisulado-700;
    border-radius: $tooltip-arrow-border-radius;
    width: $tooltip-arrow;
    height: $tooltip-arrow;
    #{$arrowX}: $arrowValue;
    #{$positionX}: calc(50% - 8px);
  }
}
`

2023-03-09 16:54 UTC, matilope commented on src/scss/components/_tooltip.scss
> +  max-width: $tooltip-max-width;
El valor de la variable debería ser 18.131rem exactamente para que no quede el "tooltip" abajo cuando haces el hover.

2023-03-09 19:17 UTC, matilope commented on src/components/Tooltip/Tooltip.stories.tsx
> +//Components
Agregale un espacio despues de //

2023-03-09 19:17 UTC, matilope commented on src/components/Tooltip/Tooltip.stories.tsx
> +//Components
Agregale un espacio despues de //

2023-03-09 19:19 UTC, matilope commented on src/components/Tooltip/index.tsx
> +  flow?: string;
No debería de ser obligatorio "flow" ? en caso de que no en las constantes de abajo podes darle un valor predeterminado por si no esta. Ademas el tipo de dato deberia ser por ej:
export type dataFlow = 'top-right' | 'top' | 'top-left'....

2023-03-09 19:39 UTC, matilope commented on src/components/Tooltip/index.tsx
> +  text?: string;
Text también debería ser obligatorio no? porque si no, no tiene sentido el componente me parece jaja.

2023-03-10 16:01 UTC, alan199912 requested changes

2023-03-10 16:02 UTC, alan199912 commented on src/components/Tooltip/index.tsx
> +  if (box) className += ` icon-box bg-light`;
Los dos comenarios que estan ocultos abrilos, no se porque se ponen asi

2023-03-10 17:59 UTC, alan199912 approved these changes

2023-03-13 18:20 UTC, merged