feat: navegacion por pestañas
gcba/Obelisco pull request #138
Opened 2023-03-09 18:32 UTC by davisLjr

Enlace a figma:
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/BnExXyHGaQePEwoeeacfN5/UI-KIT---Obelisco?node-id=659-8209&t=b7TEfa9arRkHKKnd-0
Enlace a figma estandares:
https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/kYo54WHoHw3V95BTcHTuDF/Fichas?node-id=154-813&t=XdjlPaC085Wv32i2-0

Se agrega la navegacion por pestañas.
Ancho variable, ancho fijo, con icono, desplazable y sus versiones con color de fondo.

Temas a resolver:

Diseño en mobile del componente, como seria el comportamiento del mismo.
Revision de modo de uso de iconos en navegacion horizontal y vertical, la actual logica y estilos tiene limitantes en modo de uso.

Revision de los nombres que se visualizan en storybook.

2023-03-09 18:47 UTC, davisLjr commented
faltan modificar espaciados en navegacion horizontal y vertical segun el nuevo figma.

2023-03-10 15:31 UTC, alan199912 requested changes
Porque no utilizaste la clase `nav-tabs` de bootstrap?

2023-03-10 15:31 UTC, alan199912 commented on src/scss/components/_nav.scss
> +    &.full-width {
En lugar de generar esta clase, porque no le agregas w-100 en el html

2023-03-11 15:26 UTC, davisLjr commented on src/scss/components/_nav.scss
>      &:first-child {
Ok

2023-03-11 15:26 UTC, davisLjr commented on src/scss/components/_nav.scss
>            i {
Ok

2023-03-11 15:26 UTC, davisLjr commented on src/scss/components/_nav.scss
> +      white-space: nowrap;
Perfecto ahi lo cambio.

2023-03-11 15:27 UTC, davisLjr commented on src/scss/components/_nav.scss
> +        display: flex;
el transition lo comentaré, es porque el font-weight cuando esta activo segun figma debe pasar de 400 a 700, y para que el cambio se vea mas suave le agrego un transition, de igual forma se hizo la propuesta con el text-shadow esto aun esta por confirmar cual queda o que se modifica.
En cuanto al color de fondo, se va a definir con diseño seguramente entre el lunes y martes 14/03

2023-03-11 15:27 UTC, davisLjr commented on src/scss/components/_nav.scss
> +          padding-left: $nav-link-padding-lg-y;
Si tal cual, lo mismo le habia preguntado a diseño y me confirmaron que no se va a utilizar icono sin texto pero de igual forma se cambiara a gap.

2023-03-11 15:27 UTC, davisLjr commented on src/scss/components/_nav.scss
> +          color: $nav-link-disabled-color;
se elimina y se implementa la clase.

2023-03-11 15:27 UTC, davisLjr commented on src/scss/components/_nav.scss
> +          gap: 0;
Ok

2023-03-11 15:27 UTC, davisLjr commented on src/scss/components/_nav.scss
> +    &.full-width {
Se agrega al <li> y <a> la clase w-100 con la condicional isFullWidth

2023-03-13 13:49 UTC, davisLjr commented
Se hacen los cambios correspondientes a los comentarios en el PR, se agrega variante tamaños y condicional para ancho fijo o ancho variable

2023-03-13 15:38 UTC, matilope commented on src/components/Nav/index.tsx
> +  iconTabs?: string;
Aca podes inferirle el tipado de esta forma:

`import React, { ReactElement } from 'react';`

`iconTabs?: ReactElement<HTMLSpanElement>;`


al hacer esto vas a tener que cambiar muchas cosas igual pero como lo habiamos hablado el jueves pasado o el anterior que me preguntaste te lo respondo ahora que acabo de fijarme bien. ahi te comento los otros cambios que deberias hacer para que funcione. en caso de que tengas curiosidad

2023-03-13 15:40 UTC, matilope commented on src/components/Nav/tabs.tsx
> +        {hasIcon && iconTabs ? (
aca quedaría asi y lo mismo va en los otros lados en que pones esto

```
{hasIcon && iconTabs ? (
          <div className="nav-icon">
            {name} {iconTabs}
          </div>
        ) : (
          <>{name}</>
        )}
```

2023-03-13 15:40 UTC, matilope commented on src/components/Nav/TabsContainer.stories.tsx
> +  { name: 'Pestaña predeterminada', id: '2', iconTabs: '<span class="material-icons-round">home</span>' },
y aca y en casos similars iria asi el objeto:

```
const sliderItems: NavItem[] = [
  { name: 'Pestaña activa', id: '1', iconTabs: <span className="material-icons-round">home</span> },
  { name: 'Pestaña predeterminada', id: '2', iconTabs: <span className="material-icons-round">home</span> },
  { name: 'Pestaña predeterminada', id: '3', iconTabs: <span className="material-icons-round">home</span> },
  { name: 'Pestaña predeterminada', id: '4', iconTabs: <span className="material-icons-round">home</span> },
  { name: 'Pestaña predeterminada', id: '5', iconTabs: <span className="material-icons-round">home</span> },
  { name: 'Pestaña predeterminada', id: '6', iconTabs: <span className="material-icons-round">home</span> },
  { name: 'Pestaña predeterminada', id: '7', iconTabs: <span className="material-icons-round">home</span> },
  { name: 'Pestaña predeterminada', id: '8', iconTabs: <span className="material-icons-round">home</span> },
  { name: 'Pestaña predeterminada', id: '9', iconTabs: <span className="material-icons-round">home</span> },
  {
    name: 'Pestaña deshabilitada',
    id: '10',
    disabled: true,
    iconTabs: <span className="material-icons-round">home</span>
  }
];
```

2023-03-14 14:27 UTC, davisLjr commented on src/components/Nav/index.tsx
> +  iconTabs?: string;
Guarde esto en un archivo aparte, si llega a ser necesario se suben los nuevos cambios.

2023-03-14 14:27 UTC, davisLjr commented on src/components/Nav/tabs.tsx
> +        {hasIcon && iconTabs ? (
Guarde esto en un archivo aparte, si llega a ser necesario se suben los nuevos cambios.

2023-03-16 18:21 UTC, matilope commented
También podes hacer algo así para que si se desplazan pero se quedan el mouse encima del anchor no quede seleccionado / no se le ponga la clase active

`  const handleTabClick = (event: React.MouseEvent<HTMLAnchorElement>) => {
    const tab = event.currentTarget;
    const tabsBox = tabsBoxRef.current;
    if (!tabsBox) return;
    setScrollLeft(tabsBoxRef?.current?.scrollLeft);
    if (scrollLeft == tabsBoxRef?.current?.scrollLeft) {
      const activeTab = tabsBox.querySelector('.active');
      if (activeTab) {
        const duration = 500;
        setTimeout(() => {
          activeTab.classList.remove('active');
          tab.classList.add('active');
        }, duration);
      } else {
        tab.classList.add('active');
      }
    }
  };`
  
  y...
  
  
  `
  const handleMouseDown = (event: React.MouseEvent<HTMLUListElement>) => {
    setIsDragging(true);
    const tabsBox = tabsBoxRef.current;
    if (!tabsBox) return;
    setStartX(event.pageX - tabsBox.offsetLeft);
    setScrollLeft(tabsBox.scrollLeft);
  };
`

2023-03-22 15:36 UTC, davisLjr commented
Se agregan dos props, withButton y classUl, se elimina isFullWidth y clases w-100, segun la propuesta presentada a diseño, pasamos a usar el mismo componente slider con y sin botones como variantes respetando el diseño de figma, queda por confirmar el ancho minimo del la variante " ancho fijo ", y el gap entre icono y texto que varia en el diseño de figma.

2023-03-22 17:04 UTC, Jesus1397 commented on src/components/Nav/Nav-horizontal.stories.tsx
Fijate que se queja de que le falta el atributo classUl en los NavHorizontal

2023-03-22 17:15 UTC, Jesus1397 commented on src/components/Nav/Nav.stories.scss
> +  @media only screen and (max-width: 768px) {
Agregale un salto de linea y formatealo con prettier

2023-03-22 17:26 UTC, Jesus1397 commented on src/scss/components/_nav.scss
> +          //font-weight: $nav-link-font-weight;
Esto tambien quedo comentado

2023-03-22 17:31 UTC, davisLjr commented on src/scss/components/_nav.scss
> +          //font-weight: $nav-link-font-weight;
Esta comentado ya que falta definir con diseño.

2023-03-22 17:31 UTC, davisLjr commented on src/scss/components/_nav.scss
> +        //transition: font-weight 0.2s ease;
Esta comentado ya que falta definir con diseño.

2023-03-22 17:32 UTC, Jesus1397 commented on src/scss/components/_nav.scss
> +        background-color: pink !important;
Te olvidaste borrar esto

2023-03-22 17:38 UTC, davisLjr commented on src/components/Nav/Nav.stories.scss
> +  @media only screen and (max-width: 768px) {
se soluciona en el siguiente commits

2023-03-22 17:39 UTC, davisLjr commented on src/components/Nav/Nav-horizontal.stories.tsx
se corrigio la interface solventando el error.

2023-03-22 17:43 UTC, davisLjr commented
se agregan correcciones sugeridas en los comentarios del PR, background de prueba fue eliminado, y salto de linea en hoja de estilos

2023-03-22 19:12 UTC, alan199912 requested changes

2023-03-22 19:12 UTC, alan199912 commented on src/components/Nav/tabs.tsx
> +      <nav className={`tabs-slider${!isWithButton ? ' px-0' : ''}`}>
separa con un espacio antes de las `{}` y no agregar ese mismo espacio en `px-0`

De esta manera queda mas legible el codigo

2023-03-22 19:12 UTC, alan199912 commented on src/components/Nav/tabs.tsx
Tanto en el metodo `handleMouseLeave` como en los demas, podes declararlo en una sola linea, ya que solo el metodo se encarga de setear el estado en falso.

Ejemplo

```
const handle = () => setState(flase);
```

2023-03-22 19:12 UTC, alan199912 commented on src/scss/components/_nav.scss
> +  &.tabs {
Tratemos de darle un poco mas de aire a las clases, esta todo junto y se hace complicado leer el codigo.

Ejemplo:

```
&.class-1 {
    width: auto;
    width: auto;
    width: auto;
    
  .class-2 {
     width: auto;
     width: auto;
     
     .class {
         width: auto;
      }
   }
   
   .class-4 {
      width: auto;
    }
}
```

2023-03-22 21:13 UTC, davisLjr commented on src/components/Nav/tabs.tsx
Se soluciona en el proximo commits.

2023-03-22 21:13 UTC, davisLjr commented on src/components/Nav/tabs.tsx
> +      <nav className={`tabs-slider${!isWithButton ? ' px-0' : ''}`}>
Se soluciona en el proximo commits.

2023-03-28 12:59 UTC, davisLjr commented on src/scss/components/_nav.scss
> +        gap: 0.625rem;
Se define que el gap entre icono y texto en navegacion horizontal y vertical es de 4px y en pestañas es de 10px

2023-03-28 18:26 UTC, davisLjr commented on src/scss/components/_nav.scss
> +        gap: 0.625rem;
se soluciona en el proximo commits

2023-03-30 19:22 UTC, davisLjr commented on src/scss/components/_nav.scss
> +          //font-weight: $nav-link-font-weight;
Definido por diseño va font-weight, se soluciona en proximo commits.

2023-04-12 16:09 UTC, matilope commented
Quiza el text-shadow puede ser: 0px -0.6px 0px #38485c

Asi no se separa tanto del texto, cuando esta en -1 se aleja mucho y si le haces zoom podes ver que se separa del texto original.

No se si seria suficiente shadow ahi para simular el font weight pero bueno.

2023-04-13 13:20 UTC, alan199912 requested changes

2023-04-13 13:20 UTC, alan199912 commented on src/scss/components/_nav.scss
> +$nav-link-padding-x: 1.125rem;
Seprara las variables para nav y tabs

2023-04-13 20:32 UTC, alan199912 approved these changes

2023-04-14 12:42 UTC, lautarorodriguez96 approved these changes

2023-04-14 12:57 UTC, merged