fix: spinner y boton con spinner
gcba/Obelisco pull request #142
Opened 2023-03-22 20:49 UTC by victorianastasi

Se modifica componente spinner: se agrega Tamaños y Expandible, se modifica "Sin mensaje" por "Predeterminado" y se elimina "Con mensaje"
Se agrega en Botones: "Con spinner"
Figma: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/AvjnjMjNe1gyOCMfjPZIuO/UI-KIT---Obelisco?node-id=870-7996&t=wRFHcLWEYBKGveLj-0

2023-03-23 13:37 UTC, Jesus1397 commented on src/components/Spinner/Spinner.stories.tsx
> +      <span className="sr-only">Loading...</span>
Hace algo el texto de "Loading" ?

2023-03-23 13:49 UTC, Jesus1397 commented on src/scss/components/_spinner.scss
> +$spinner-width: 2rem;
Si no las usas borralas o crea variables para spinner-sm y spinner-lg

2023-03-23 13:58 UTC, Jesus1397 commented on src/components/Button/Button.stories.tsx
> +      <button className="btn btn-link btn-icon btn-sm">
Podrias modificar el componente de Button para que acepte spinner y asi evitar usar mucho codigo

2023-03-23 15:19 UTC, alan199912 requested changes

2023-03-23 15:19 UTC, alan199912 commented on src/scss/components/_spinner.scss
> +    &-sm {
Agregale un enter aca

2023-03-23 15:20 UTC, alan199912 commented on src/scss/components/_spinner.scss
> +$spinner-width: 2rem;
Las usa, esta sobreescribiendo las variables de bootstrap

2023-04-18 19:42 UTC, victorianastasi commented on src/components/Button/Button.stories.tsx
> +      <button className="btn btn-link btn-icon btn-sm">
gracias!

2023-04-18 19:43 UTC, victorianastasi commented on src/components/Spinner/Spinner.stories.scss
> +  &-size {
se modifico spinner expandible y se elimino esa clase, gracias!

2023-04-18 19:47 UTC, victorianastasi commented
Modificaciones en spiner: se agrega tipos.

Figma Spinner: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/AvjnjMjNe1gyOCMfjPZIuO/UI-KIT---Obelisco?node-id=1152-14221&t=f47rDgEDr3xbVe52-0

Figma Botones con spinner: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/Am0LZV3t3wEaQsx1iiBQhC/UI-KIT---Obelisco?node-id=4694-27435&t=naGnwTJOOhsupVSt-0

Pendiente: modificar estilos para que el borde del spinner sea redondeado

2023-04-20 18:04 UTC, matilope commented on src/components/Spinner/Spinner.stories.tsx
> +// Components
Esto lo pondría arriba del comentario de "Configuración general del componente" (linea 8), asi queda ordenado al igual que el resto de los componentes.

2023-04-20 18:07 UTC, matilope commented on src/scss/components/_spinner.scss
> +
Mnadale un format document asi se quita este espacio

2023-04-20 20:02 UTC, alan199912 requested changes
Cambiar la rama a donde apunta

2023-04-21 13:33 UTC, lautarorodriguez96 approved these changes
Subimos asi como primer version de spinner
Desde fix_spinner se hace la nueva branch de botones

2023-04-21 13:37 UTC, davisLjr approved these changes

2023-04-21 13:54 UTC, matilope approved these changes

2023-04-21 14:12 UTC, merged