feat: Alerta - Tooltip - Paginador - Breadcrumb
gcba/Obelisco pull request #143
Opened 2023-04-04 20:09 UTC by lautarorodriguez96

2023-04-04 20:27 UTC, alan199912 requested changes

2023-04-04 20:27 UTC, alan199912 commented on src/version/Version.stories.tsx
> +        href="https://github.com/gcba/Obelisco/releases/tag/v1.47.0"
Agregaria este enlace asi no tenemos que configurar siempre el numero de la version:

https://github.com/gcba/Obelisco/releases/latest


Siempre te muestra la ultima

2023-04-04 20:31 UTC, alan199912 requested changes

2023-04-04 20:31 UTC, alan199912 commented on src/version/Version.stories.tsx
> +    <h1>Versión Obelisco 1.47.0</h1>
Tambien para no estar cambiando siempre el numero de la version podemos consumir el endpoint de github, en este caso seria:
https://api.github.com/repos/gcba/Obelisco/releases/latest
Y el tag seria la propiedad `tag_name`

2023-04-10 14:08 UTC, lautarorodriguez96 commented on src/version/Version.stories.tsx
> +    <h1>Versión Obelisco 1.47.0</h1>
Cambiando el enlace de arriba, y cambiando "versión actual" es el único numero de versión que quedaría actualizar.

2023-04-10 14:26 UTC, alan199912 commented on src/version/Version.stories.tsx
> +    <h1>Versión Obelisco 1.47.0</h1>
Cambio realizado!

2023-04-13 19:14 UTC, davisLjr approved these changes

2023-04-14 17:54 UTC, davisLjr approved these changes

2023-04-14 17:57 UTC, alan199912 approved these changes

2023-04-14 17:59 UTC, merged