fix: progressbar
gcba/Obelisco pull request #146
Opened 2023-04-18 20:02 UTC by Jesus1397

-Se paso de componente html a react 
-Se cambio el nombre de los tipos a "simple" y "con descripción"

UI Kit:
https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/28xf3UMJJ2qeHhRrVaAVh7/UI-KIT---Obelisco?node-id=2798-12566&t=ry6le3tEPG5GJl2F-0

Ficha de Estandares:
https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/me67uDBH1pmTRAYQwmIsyj/Fichas?node-id=534-812&t=rdltmFvsiWRdZADn-0

2023-04-20 14:28 UTC, matilope commented on src/components/ProgressBar/ProgressBar.stories.tsx
> +simple.story = { name: 'Simple' };
Esto no hace falta porque de por si ya se pone como "Simple" en la historia.

2023-04-20 18:45 UTC, alan199912 requested changes
A la clase `.progress-bar` le falta agregar el borde.
![image](https://user-images.githubusercontent.com/40763553/233459053-42f7060e-03be-443b-9551-5e8cc1eca6dc.png)

2023-04-20 19:18 UTC, lautarorodriguez96 approved these changes

2023-04-21 12:52 UTC, matilope approved these changes

2023-04-21 13:58 UTC, victorianastasi approved these changes

2023-04-21 14:14 UTC, merged