Fix footer
gcba/Obelisco pull request #147
Opened 2023-04-20 12:51 UTC by lautarorodriguez96

2023-04-20 13:00 UTC, lautarorodriguez96 commented
Falta confirmar:
Si cambio el espaciado de links rrss entre figma y story
Si cambio el orden de 144 y 147 (antes 147 - 144)

2023-04-20 18:48 UTC, alan199912 requested changes
Agrega los links de figma.
Hay que corregir el nombre del pr, para que sea `feat: footer` por ejemplo

2023-04-21 14:16 UTC, victorianastasi commented on src/scss/components/_footer.scss
en figma, el font-weight de phone-items es 400

2023-04-21 14:23 UTC, victorianastasi commented on src/organisms/Footer/Footer.stories.tsx
>  const LegalSection = (): JSX.Element => (
Los iconos de SocialSection son distintos en figma, se modifican?

2023-04-21 14:38 UTC, Jesus1397 reviewed
Los enlaces de "Terminos y condiciones" y "Oficios judiciales" redireccionan a pagina no encontrada, o no funciona la pagina o cambiaron la url

Encontre estas en google:
https://buenosaires.gob.ar/jefaturadegabinete/innovacion/terminos-y-condiciones 

https://buenosaires.gob.ar/tramites/oficios-judiciales

2023-04-24 13:34 UTC, matilope commented
Según el Figma:

* Los h4 dentro del .main-footer figuran con un margen inferior de 0.5rem en escritorio y 1rem en mobile.
* El hr deberia tener un margin superior e inferior de 2.5rem en escritorio y de 2rem en mobile.
* footer-content-img en mobile deberia tener un margen inferior de 1.5rem.
* Los list-inline-item en mobile deberian tener un margen inferior de 1rem.
* El footer-legal-section en mobile deberia tener un margen inferior de 1.5rem.

2023-04-24 18:15 UTC, lautarorodriguez96 commented
> Según el Figma:
> 
> * Los h4 dentro del .main-footer figuran con un margen inferior de 0.5rem en escritorio y 1rem en mobile.
> * El hr deberia tener un margen superior e inferior de 2.5rem en escritorio y de 2rem en mobile.
> * footer-content-img en mobile deberia tener un margen inferior de 1.5rem.
> * Los list-inline-item en mobile deben tener un margen inferior de 1rem.
> * Los phone-items y redes-items deben tener un margen derecho de 1rem.
> * El footer-legal-section en mobile deberia tener un margen inferior de 1.5rem.
> * El padding del footer deberia ser 2.5rem en escritorio y 2rem en mobile

Lo revisamos con diseño los nuevos espaciados y corregimos si hacen falta

2023-04-24 18:54 UTC, lautarorodriguez96 commented
> Los enlaces de "Terminos y condiciones" y "Oficios judiciales" redireccionan a pagina no encontrada, o no funciona la pagina o cambiaron la url
> 
> Encontre estas en google: https://buenosaires.gob.ar/jefaturadegabinete/innovacion/terminos-y-condiciones
> 
> https://buenosaires.gob.ar/tramites/oficios-judiciales

Se modificó el de terminos y condiciones.
Oficios judiciales esta bien, solo que no funciona en D8

2023-04-24 19:09 UTC, victorianastasi commented on src/organisms/Footer/Footer.stories.tsx
>  const LegalSection = (): JSX.Element => (
Me referia al ultimo footer que esta en figma, si es que se agrega por separado a storybook o no es necesario
![image](https://user-images.githubusercontent.com/60082396/234092471-fa175330-2d3b-4a7e-b593-8180593f0ad0.png)

2023-04-25 17:13 UTC, lautarorodriguez96 commented on src/organisms/Footer/Footer.stories.tsx
>  const LegalSection = (): JSX.Element => (
lo consultamos

2023-04-26 14:02 UTC, matilope commented
Cosas que vi que faltan y otras que no puse:

* Los h4 dentro del .main-footer figuran con un margen inferior de 0.5rem en escritorio y 1rem en mobile.
* Los list-inline-item en escritorio y en mobile deberian tener un margen inferior de 1rem. (excepto el ultimo porque el ul ya tiene ese margen inferior)
* Los list-inline-item deberian tener un margen derecho de 1rem.

2023-04-26 17:05 UTC, Jesus1397 commented on src/scss/components/_footer.scss
> +$divier-margin: 2.5rem 0 2.5rem;
Al nombre de la variable le falta la letra D

2023-04-26 17:45 UTC, matilope commented on src/scss/components/_footer.scss
>          justify-content: space-between;
Le sacaria el justify-content y le agregaria `gap: 2rem;`
![image](https://user-images.githubusercontent.com/66441937/234660021-22fb226e-fb13-4327-ae5b-6363232ab74c.png)

![image](https://user-images.githubusercontent.com/66441937/234660086-387e0d83-41a3-4131-ab92-9c547a3ad302.png)

2023-04-26 20:41 UTC, Jesus1397 approved these changes

2023-04-26 21:00 UTC, matilope commented on src/scss/components/_footer.scss
>          justify-content: space-between;
Por las dudas paso a comentar esto:
De esta forma a los 290px se empieza a "romper" y con el space-between se empieza a "romper" a los 260px de ancho.

Romper = no hay mas espacio para la imagen y se queda ahi quieta mientras se sigue ajustando lo otro.

Pero de esta forma se muestra en el Figma, se muestra con esos 2rem de gap y no con el space-between.

Solo lo aclaro por las dudas.

2023-04-26 21:01 UTC, matilope approved these changes

2023-04-27 14:11 UTC, victorianastasi approved these changes

2023-04-27 14:22 UTC, davisLjr approved these changes

2023-05-02 18:38 UTC, merged