Navegación
gcba/Obelisco pull request #15
Opened 2020-10-29 05:28 UTC by techlowiec

Cambié los contenedores de <div> a <nav> y modifiqué los estilos en cuanto a texto y bg-color en active, hover y focus.

2020-11-03 03:52 UTC, nirougi requested changes

2020-11-03 03:52 UTC, nirougi commented on src/scss/components/_nav.scss
> +  @include border-radius($border-radius-container); //la definición de esa variable está en _miscellaneous y es .5rem
¿Por qué el comentario?
Me parece que no escala tener que hacer referencia de todas las variables que hagamos generales.

2020-11-03 03:52 UTC, nirougi commented on src/scss/components/_nav.scss
> +//Este estilo es válido pero como no está la variable $lightBlue-700 en esta branch rompe. Cuando mergeemos la branch "colors" con master y hagamos rebase de esto descomentamos.
Fijate que hice un comentario respecto al celeste.
En este caso deberíamos poder usar la función `theme-color-level('info', 3)` para obtener lo que sería el `$info-700`.

2020-11-03 03:52 UTC, nirougi commented on src/scss/components/_nav.scss
> +//Este estilo es válido pero como no está la variable $lightBlue-700 en esta branch rompe. Cuando mergeemos la branch "colors" con master y hagamos rebase de esto descomentamos.
Como extra, cuando tengas comentarios de este estilo, en vez de ponerlo en el código, conviene hacer uno de estos comentarios en el review.

2020-11-03 03:52 UTC, nirougi commented on src/scss/components/_nav.scss
> +$nav-pills-link-active-bg: $grisulado-900;
¿Dónde se definió que el color de fondo del estado activo sea gris?
Yo siempre lo vi en azul como acá abajo 🤔 

![image](https://user-images.githubusercontent.com/1561463/97948265-cd208280-1d6e-11eb-8188-44c0617d285b.png)

2020-11-03 03:56 UTC, techlowiec commented on src/scss/components/_nav.scss
> +$nav-pills-link-active-bg: $grisulado-900;
En la última actualización del UI Kit están en ese color: https://xd.adobe.com/view/c5e691f2-0643-4e9e-a769-f2252af77984-90b5/screen/13a11386-db64-4ee9-8d60-21f3ed80afa6/

2020-11-03 04:02 UTC, techlowiec commented on src/scss/components/_nav.scss
> +  @include border-radius($border-radius-container); //la definición de esa variable está en _miscellaneous y es .5rem
La verdad, lo comenté para mí porque primero busqué la variable en Bootstrap, después en los estilos del componente y estuve un rato hasta que la encontré en _miscellaneous -que nunca lo había usado-, para que a futuro tuviera la referencia.

2020-11-03 04:07 UTC, nirougi commented on src/scss/components/_nav.scss
> +$nav-pills-link-active-bg: $grisulado-900;
Ok. Para estas implementaciones tratemos de basarnos en las definiciones que acordamos y todo cambio posterior quedará para una segunda implementación de cada componente. Sino estamos todo el tiempo cambiando y nunca cerramos.

Esto igual dejémoslo así.

2020-11-05 00:56 UTC, nirougi approved these changes

2020-11-05 00:59 UTC, nirougi commented
Ahí ya lo aprobé.
Hacete el merge y cuando te deje asignar el título del nuevo commit, asegurate de que arranque con `fix:` para que salga bien la nueva versión.

2020-11-06 14:44 UTC, merged