Fix: botones
gcba/Obelisco pull request #150
Opened 2023-04-24 12:51 UTC by victorianastasi

Se modifica organización de botones en componentes y se agrega botones en organismos (antes botones en caja).
Se modifica tamaño de icono segun UI Kit

UI Kit: https://www.figma.com/file/ToGlPBzfp1gKDmaCwKWtXS/branch/Am0LZV3t3wEaQsx1iiBQhC/UI-KIT---Obelisco?node-id=4694-27435&t=pZRhlnzm8JVuUIhW-0

Ficha: https://www.figma.com/file/Pi8vXNQiMDtCNvV1aTCQX7/branch/TACkInq3BPwJ41czJNcOsT/Fichas?node-id=2136-814&t=2IcfjbVJXNdIZS1W-0

2023-04-25 13:18 UTC, lautarorodriguez96 commented on src/scss/components/_button.scss
> +      font-size: 1.25rem;
El tamaño de los iconos no es de 16px y 13px?

2023-04-25 13:27 UTC, victorianastasi commented on src/scss/components/_button.scss
> +      font-size: 1.25rem;
Use el tamaño de la caja del icono en figma, porque en storybook el icono tiene un pequeño espaciado, uso 13.33 y 16.67px?
![image](https://user-images.githubusercontent.com/60082396/234291231-91234a41-9b03-4e99-bc92-ed074424e1c8.png)
![image](https://user-images.githubusercontent.com/60082396/234291427-eedb014b-0a28-46dc-93e3-468acefa6b1d.png)

2023-04-25 14:39 UTC, alan199912 requested changes
El nombre del PR no tiene que empezar en mayuscula.

2023-04-25 19:36 UTC, lautarorodriguez96 commented on src/scss/components/_button.scss
> +      font-size: 1.25rem;
no, dejemos asi porque sino es muy chico el icono.

2023-04-26 13:44 UTC, lautarorodriguez96 approved these changes

2023-04-26 18:10 UTC, Jesus1397 commented on .storybook/preview.ts
> +      if (aHeader !== bHeader) {
Formatea el archivo

2023-04-26 20:09 UTC, Jesus1397 approved these changes

2023-04-27 20:09 UTC, lautarorodriguez96 approved these changes

2023-05-02 12:35 UTC, merged