Breadcrumb
gcba/Obelisco pull request #5
Opened 2020-09-03 13:56 UTC by ghoyos95

este pr es para que revisemos los cambios en las historias del componente breadcrumb

2020-09-09 00:45 UTC, nirougi requested changes
Separaría los diferentes breadcrumbs que agregaste en diferentes historias, asegurándonos que cada una muestre algo diferente a las otras.
También falta agregar que en teléfonos se oculten todas las del medio, solo deberían mostrarse la primera y la última.

2020-09-09 00:45 UTC, nirougi commented on .storybook/preview-head.html
> +<<<<<<< HEAD
Fijate que subiste este archivo con un conflicto.
Esto está haciendo que no pase el linter.

2020-09-09 00:45 UTC, nirougi commented on package.json
> +    "jQuery": "^1.7.4",
A estos archivos al final los estamos cargando desde un CDN, por lo que no hace falta importarlos como dependencias en este archivo.

2020-09-09 00:45 UTC, nirougi commented on src/components/Example/Example.stories.tsx
> +// Base
Fijate que le cambiaste el nombre a este archivo y eso hace que se vea en Storybook.

2020-09-09 00:45 UTC, nirougi commented on src/components/Breadcrumb/breadcrumb.stories.tsx
> +        <li className="breadcrumb-item active bread-first" aria-current="page">
¿Para qué sería la clase `bread-first`?
No veo que se le apliquen estilos ni que sea parte de bootstrap.

2020-09-09 00:45 UTC, nirougi commented on src/scss/obelisco.scss
> +@import "components/card";
Fijate que te quedón un conflicto y estás importando archivos que no existen en esta rama.
Debe ser que te quedó de cuando lo pasaste desde tu otra branch.

2020-09-09 00:45 UTC, nirougi commented on src/scss/components/_breadcrumb.scss
> +  color: $grisulado-900;
Bien ahí usando las variables! 🙌

2020-09-09 00:45 UTC, nirougi commented on src/components/Breadcrumb/breadcrumb.stories.tsx
> +        <li className="breadcrumb-item active" aria-current="page">
Tené en cuenta que no estamos mostrando la página actual, por lo que este último elemento también debería ser cliqueable.

2020-09-09 17:32 UTC, ghoyos95 commented on src/scss/obelisco.scss
> +@import "components/card";
ok!

2020-09-09 18:17 UTC, ghoyos95 commented on package.json
> +    "jQuery": "^1.7.4",
bastaria con borrar estas dos lineas entonces ?

2020-09-09 18:17 UTC, ghoyos95 commented on package.json
> +    "jQuery": "^1.7.4",
@nirougi

2020-09-09 18:20 UTC, ghoyos95 commented on src/components/Breadcrumb/breadcrumb.stories.tsx
> +        <li className="breadcrumb-item active" aria-current="page">
bien !

2020-09-09 18:31 UTC, ghoyos95 commented on src/components/Breadcrumb/breadcrumb.stories.tsx
> +        <li className="breadcrumb-item active bread-first" aria-current="page">
es verdad, para nada. creo que había hecho unas pruebas para insertar un icono pero al final no iba

2020-09-18 18:52 UTC, nirougi commented on package.json
> +    "jQuery": "^1.7.4",
Recién veo esto, no me llegó la notificación u.u
Sí, con borrarlo alcanza.

2020-09-23 04:01 UTC, nirougi commented
@ghoyos95 fijate que quedaron algunos comentarios en más arriba que no están resueltos.

2020-09-23 17:02 UTC, ghoyos95 commented on .storybook/preview-head.html
> +<<<<<<< HEAD
done

2020-09-23 17:03 UTC, ghoyos95 commented on package.json
> +    "jQuery": "^1.7.4",
done

2020-09-23 17:03 UTC, ghoyos95 commented on src/components/Breadcrumb/breadcrumb.stories.tsx
> +        <li className="breadcrumb-item active bread-first" aria-current="page">
done

2020-09-23 17:06 UTC, ghoyos95 commented on src/components/Breadcrumb/breadcrumb.stories.tsx
> +        <li className="breadcrumb-item active" aria-current="page">
done

2020-09-23 17:07 UTC, ghoyos95 commented on src/components/Example/Example.stories.tsx
> +// Base
@nirougi queda pendiente este tema que no entiendo muy bien porque ahora no lo veo... cuando peudas lo vemos

2020-10-14 04:47 UTC, nirougi requested changes

2020-10-14 04:47 UTC, nirougi commented on src/components/Breadcrumb/breadcrumb.stories.tsx
> +        <li className="breadcrumb-item active bread-first" aria-current="page">
Sigue estando.

2020-11-06 03:56 UTC, nirougi approved these changes

2020-11-06 03:56 UTC, merged