refactor accesos
gcba/Obelisco pull request #50
Opened 2022-02-24 15:23 UTC by alan199912

Se han modificado estilos de los accesos y creado nuevos tipos.
segun el [New Ui-kit](#https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/2eb5fc6f-0ef9-474a-9ec8-4b9fe64ebec2/specs/)

2022-03-08 04:32 UTC, nirougi requested changes
Te fui dejando algunos comentarios en el código.

Lo más importante es el tema de bordes porque al hacer hover se cambian los tamaños de los elementos y queda raro el comportamiento.

También veamos los espaciados de los accesos grandes, porque están muy separados, dejo una referencia:

<img width="350" alt="Screen Shot 2022-03-08 at 01 32 11" src="https://user-images.githubusercontent.com/1561463/157166639-be89e0ce-93e9-4a6d-8cd1-bc7b3550890e.png">

2022-03-08 04:32 UTC, nirougi commented on src/components/List-group/AccessList.stories.tsx
> +                  <a href="javascript:void(0)" className="list-group-item item-sm">
Para los `href` en general usamos el valor `#` para evitar confusiones.

2022-03-08 04:32 UTC, nirougi commented on src/components/List-group/ListAccessDescriptive.stories.tsx
> +                  <a href="j#" className="list-group-item item-sm">
Detalle super menor, pero se escaparon unas `j` en los `href`.

2022-03-08 04:32 UTC, nirougi commented on src/components/List-group/ListAccessDescriptive.stories.tsx
> +                <i className="bx bxs-shield-x card-access-icon bx-flip-horizontal"></i>
¿Por qué usamos usamos la clase `bx-flip-horizontal`?

2022-03-08 04:32 UTC, nirougi commented on src/scss/components/_list-group.scss
>  $list-group-color: #007bc7;
Al `$list-group-color` lo estamos definiendo dos veces, está también más arriba.
Para colores, deberíamos usar las variables de grisulado o la función `theme-color-level`

2022-03-08 04:32 UTC, nirougi commented on src/scss/components/_list-group.scss
> +$list-group-hober-bg: #f3f6f9;
Hay un typo en `hover` y el color idealmente debería venir de la paleta usando la función `theme-color-level` o alguna función de sass.

2022-03-08 04:32 UTC, nirougi commented on src/scss/components/_list-group.scss
> +    border: $border-access-hover;
Para estos casos tenemos que tener en cuenta que agregando bordes cambia el tamaño de la caja.
En general solemos usar el box-shadow en vez del borde para evitar eso.

Fijate cómo está en las cards para tener de referencia.

2022-03-08 04:32 UTC, nirougi commented on src/scss/components/_list-group.scss
> +    box-shadow: $box-shadow-access-focus;
Genial el uso de variables acá 🙌

2022-03-08 15:28 UTC, alan199912 commented on src/components/List-group/AccessList.stories.tsx
> +                  <a href="javascript:void(0)" className="list-group-item item-sm">
Corregido !

2022-03-08 15:29 UTC, alan199912 commented on src/components/List-group/ListAccessDescriptive.stories.tsx
> +                <i className="bx bxs-shield-x card-access-icon bx-flip-horizontal"></i>
Debi copiar mal en la pagina de los iconos, lo corregi !

2022-03-08 15:29 UTC, alan199912 commented on src/scss/components/_list-group.scss
> +$list-group-hober-bg: #f3f6f9;
Corregifo ! Se elimino esa variable ya que no estaba siendo uitlizada, junto con otros !

2022-03-08 15:29 UTC, alan199912 commented on src/scss/components/_list-group.scss
> +    border: $border-access-hover;
Corregido !

2022-03-09 03:47 UTC, nirougi requested changes
¡Muy bueno el avance!
Hay un par de cosas visuales que deberíamos ajustar para que quede más parecido al diseño, son detalles pero deberíamos acomodarlos también:

1. Fijate que el hover debería tener el color azul (el grande lo tiene pero el chico no) y el subrayado en el texto tanto en accesos chicos como grandes.
2. Por alguna razón estoy viendo los accesos grandes de la historia **Lista de accesos** en azul 🤔 
  ![Raaaro](https://user-images.githubusercontent.com/1561463/157368343-3bde3899-a73b-4ea4-8206-d5ec524aa371.png)
3. La lista de accesos con categoría tiene un espacio más grande entre el `card-access-body` y la línea que separa con el resto del contenido. Por ahí el ícono le está agregando un margen extra.
4. En la lista de Accesos descriptivos deberíamos tener la posibilidad de usar un número en vez de un ícono en vez de un ícono. En el diseño dice `Nº` pero deberíamos probar con dígitos reales.

Con eso ya deberíamos estar, a nivel código lo veo muy bien.

2022-03-11 03:20 UTC, nirougi approved these changes

2022-03-11 03:24 UTC, nirougi commented
¡Ahí ya está aprovado el PR!
Algo a tener en cuenta es que hacemos "Squash and merge" que va a hacer que quede un solo commit con todos los cambios y al momento de hacerlo hay que modificar el nombre del commit para agregar el prefijo.

Al estar agregando un componente nuevo deberíamos usar `feat:`.
Si querés consultalo bien con Lauti y Martín que ya lo han hecho antes.

2022-03-11 13:29 UTC, merged

2022-03-12 13:04 UTC, nirougi commented
@alan199912 Fijate que al hacer el merge y squash no pusiste el prefijo, por lo que no se publicó la versión nueva con los cambios de acceso.

[Este commit](https://github.com/gcba/Obelisco/commit/dbeb78cb82e5f9a3985680dcb9332742b85ec79e), en vez de tener de mensaje `refactor accesos (#50)` tendría que haber sido `feat: refactor accesos (#50)`.

En [la wiki](https://github.com/gcba/Obelisco/wiki/versionado-y-publicaci%C3%B3n) está un poco más explicado, pero igual hablalo con Martín y Lauti que ya lo han hecho antes.

Para que salga esta versión yo voy a estar subiendo un cambio mínimo pero con el prefijo para forzarlo.