Nuevo paginado
gcba/Obelisco pull request #53
Opened 2022-03-07 15:12 UTC by alan199912

Se ha modificado el funcionamiento del paginado junto a sus estilos.
segun el [New Ui-kit](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/2cf15d7d-0492-4559-82bd-2a5e0b58fe13/)

2022-03-09 03:27 UTC, nirougi requested changes
A los cambios los veo muy bien, pero hay un par de cosas que deberíamos ajustar antes de publicarlo.

2022-03-09 03:27 UTC, nirougi commented on src/components/Pagination/index.tsx
> +  isShowPrev?: boolean;
`isShowPrev` y `isShowNext` no deberían ser props, sino que deberíamos calcularlo en base a la página que esté seleccionada. Deberíamos modificar el `isPrevDisabled` para que en vez de mostrarlo deshabilitado lo oculte.

2022-03-09 03:27 UTC, nirougi commented on src/components/Pagination/index.tsx
> +  isHoverItem?: boolean;
`isHoverItem` y `isFocusItem` tampoco deberían ser props, sino que tendríamos que usar el css en vez de agregarle clases. La idea es que estos componentes funcionen bien solamente con html estático y css (a excepción de casos como ocultar el anterior y siguiente) y que haya la menor cantidad de lógica en react.

2022-03-09 03:27 UTC, nirougi commented on src/scss/components/_pagination.scss
> +$border-radius: 8px;
Fijate que en `scss/variables/_miscellaneous.scss` tenemos algunas constantes definidas, una de ellas es `$border-radius-lg` que define esto mismo. La idea es basarnos en esas definiciones generales para tener homogeneidad y que sea más fácil actualizar esos valores si en el futuro cambian.

2022-03-09 03:27 UTC, nirougi commented on src/scss/components/_pagination.scss
> +$pagination-icon-left-hover: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 24 24" style="fill:rgb(0,123,199);transform:;-ms-filter:"><path d
Esto está perfecto, el código que estaba comentado estaba causando errores en una de las implementaciones.
No es lo ideal tener todos los SVGs separados, pero por el momento es preferible así.

2022-03-09 03:27 UTC, nirougi commented on src/scss/components/_pagination.scss
> +      display: flex;
Fijate que varias de estas definiciones como el color, borde y color de fondo en bootstrap están dadas por variables que nosotros podemos sobreescribir y así evitarnos re definir esas propiedades.

Para ver qué variables se usan podés ver el archivo `/node_modules/bootstrap/scss/_pagination.scss`.

Con definir bien los valores al inicio de este archivo ya es suficiente. Fijate [esta parte de la wiki](https://github.com/gcba/Obelisco/wiki/crear-o-modificar-un-componente#modific%C3%A1-las-variables-de-bootstrap) que habla de eso.

2022-03-09 03:27 UTC, nirougi commented on src/scss/components/_pagination.scss
> +        border: 2px solid $blue;
Acá está pasando lo mismo que con accesos, al tener diferentes `border-width` entre el estado inicial y el hover los elementos cambian el tamaño y mueven todo. Si sabemos que son de grosores diferentes es preferible usar el box shadow para evitar ese comportamiento raro.

2022-03-09 19:42 UTC, alan199912 commented on src/components/Pagination/index.tsx
> +  isShowPrev?: boolean;
Corregido !

2022-03-09 19:42 UTC, alan199912 commented on src/components/Pagination/index.tsx
> +  isHoverItem?: boolean;
Corregido !

2022-03-09 19:44 UTC, alan199912 commented on src/scss/components/_pagination.scss
> +      display: flex;
Bien, en **active** no funciona sobreescribirle la  variable  `$pagination-active-color` que funciona como background-color por lo tanto le tuve que agregar en la clase.
Lo mismo paso con Navegacion de pagina, tuve que agregarle su `color`, `hover`, `active` y `focus` porque no las respetaba.

2022-03-09 19:44 UTC, alan199912 commented on src/scss/components/_pagination.scss
> +        border: 2px solid $blue;
Corregido !

2022-03-11 03:38 UTC, nirougi requested changes
Dos cosas a revisar antes de publicar, en general está bien.

1. En la navegación de página cuando cliqueás uno de los botones el otro también cambia de color. En este ejemplo estaba cliqueando la de la izquierda.
<img width="605" alt="image" src="https://user-images.githubusercontent.com/1561463/157797339-a3c64588-7a69-4bb3-a4bd-6387dc8c407f.png">

2. En la paginación, los elementos con tres puntos no deberían ser interactivos porque no hacen nada, hoy en día tienen tanto el hover como el focus.
<img width="321" alt="image" src="https://user-images.githubusercontent.com/1561463/157797462-43ebdc40-c7c9-4499-84e5-60112afbf547.png">

2022-03-22 15:31 UTC, lautarorodriguez96 reviewed
Lo veo bien, lo unico que al hacer click en el numero de una página en focus queda en color negro

2022-03-31 20:28 UTC, lautarorodriguez96 approved these changes

2022-04-01 12:16 UTC, lautarorodriguez96 approved these changes

2022-04-01 12:17 UTC, merged