feat - nuevos botones
gcba/Obelisco pull request #58
Opened 2022-03-11 16:15 UTC by alan199912

Se ha modificado los estilos de los botones.
segun el [New Ui-kit](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/specs/)

2022-03-15 15:59 UTC, lautarorodriguez96 commented on src/scss/components/_button.scss
>    &:disabled,
El deshabilitado en el XD pierde el color blanco, solo queda en gris

2022-03-15 17:22 UTC, lautarorodriguez96 reviewed
En el deshabilitado sacar la opcion del color  blanco

2022-03-15 18:21 UTC, alan199912 commented on src/scss/components/_button.scss
>    &:disabled,
Corregido !

2022-03-29 05:50 UTC, techlowiec requested changes
Algunos comentarios:
- [x] En los cambios nuevos tanto `.btn` como `.btn-lg` tienen un `font-size` de 18px (1.125rem). Nos falta implementarlo en el primero.
- [ ] El `padding-top` y `-bottom` de `.btn` cambia a 8px (hoy 6px).
- [x] El anillo de foco cambia a .25rem (hoy .2rem).

  ¡Buen avance con todo este componente!

2022-03-31 15:07 UTC, techlowiec approved these changes

2022-03-31 20:10 UTC, techlowiec approved these changes

2022-03-31 23:34 UTC, merged