feat: Nuevo modal
gcba/Obelisco pull request #60
Opened 2022-03-28 15:29 UTC by alan199912

Se ha modificado los estilos del modal según el [New Ui-kit](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/d2792c79-7a7d-444c-af65-474b0a8640a3/specs/)

2022-03-29 05:29 UTC, techlowiec requested changes
¡Lo veo muy bien! Un par de ajustes y estaría listo :)

2022-03-29 05:29 UTC, techlowiec commented on src/scss/components/_modal.scss
> +        margin-left: 0;
En el UI Kit hay una separación de 16px entre los botones y hoy es de 12px. Para igualar eso sin tocar los estilos de los botones podemos declarar un `gap: spaceUnits(1);` dentro de `.modal-footer` y lo soluciona.

Por otro lado, si bien es algo que estaba así, ¿nos sirve de algo sacarle el `margin-left` al primer elemento como para mantener esa declaración o es mejor borrarlo y acortar el código?

2022-03-29 05:29 UTC, techlowiec commented on src/scss/components/_modal.scss
> +      padding-bottom: 0.4rem;
¡Cuidado con este cambio! El `padding-top` quedó en 16px cuando debería ser de 24px.
Pasa la misma diferencia en `.modal-footer`: hoy es de `.625rem` cuando debería ser de `.875rem` para llegar a 24px sumando el `margin-bottom` de los botones.

2022-03-29 13:10 UTC, alan199912 commented on src/scss/components/_modal.scss
> +      padding-bottom: 0.4rem;
Se corrigio el `padding-top` !
Para el `.modal-footer` se utilizo 1.125rem ( mas 6px de los botones ) para llegar a 24px

2022-03-31 05:08 UTC, techlowiec approved these changes

2022-03-31 23:12 UTC, merged