feat: nuevo footer
gcba/Obelisco pull request #69
Opened 2022-05-06 16:08 UTC by alan199912

Se ha modificado el footer segun el [nuevo diseño](https://xd.adobe.com/view/756054ec-3c46-4d88-80f8-2582c9dc348f-2033/screen/baffc5da-aa2f-4365-a055-f025ca1426db/specs/).

2022-05-09 21:50 UTC, lautarorodriguez96 reviewed
Lo veo bien, habria que buscarle la vuelta para que tome todo el ancho el footer y no queda la linea divisora con un ancho fijo

2022-05-16 03:28 UTC, techlowiec requested changes
Buenísimo. En general re va y hay detalles que, si bien están diferentes quedan mejor así (el texto de Creative Commons está un poco más grande que en XD pero mejor así porque facilita la lectura; "Género" en XD está con mayúsculas pero buscando en otras partes de gobierno lo muestran siempre con minúscula así que mejor no tocarlo).

Dejé un par de comentarios para revisar y no mucho más que eso.

2022-05-16 03:28 UTC, techlowiec commented on src/components/Footer/footer.stories.tsx
>      <div className="container">
La lista de teléfonos tiene un espacio entre elementos de 24px y la de legales de 32px. Hoy todas están teniendo 32px de separación porque usan las mismas clases. ¿Usamos una clase nueva para diferenciarlas o qué solución les parece mejor?

2022-05-16 03:28 UTC, techlowiec commented on src/components/Footer/footer.stories.tsx
>        <PhonesSection />
Los enlaces en la lista de teléfonos tienen un peso tipográfico de 600 (semibold) y hoy están en 400 (normal). Si los pasamos sin ajustar el espacio entre elementos se va a ir a dos líneas, por eso son dos cambios a hacer juntos.

2022-05-16 03:28 UTC, techlowiec commented on src/components/Footer/footer.stories.tsx
> +        <img className="img-vamos-ba" src="footer/vamos-ba.svg" alt="Vamos Buenos Aires" height="38" />
Duda: ¿por qué no declaramos el `height` siempre desde CSS?

2022-05-16 15:42 UTC, alan199912 commented on src/components/Footer/footer.stories.tsx
>        <PhonesSection />
Corregido !

2022-05-23 16:36 UTC, techlowiec approved these changes

2022-05-23 16:36 UTC, techlowiec commented on src/scss/components/_footer.scss
> +          height: 38px;
Lo único que cambiaría es estos valores de `px` a `REM`para que no queden en unidades absolutas.
Nada más aparte de eso.

2022-05-23 17:32 UTC, alan199912 commented on src/scss/components/_footer.scss
> +          height: 38px;
Corregido !

2022-05-23 17:41 UTC, lautarorodriguez96 approved these changes

2022-05-23 17:41 UTC, merged