Chip bottom
gcba/Obelisco pull request #70
Opened 2022-05-09 15:27 UTC by lautarorodriguez96

2022-05-09 16:21 UTC, alan199912 requested changes

2022-05-09 16:21 UTC, alan199912 commented on src/scss/components/_button.scss
> +    color: $grisulado-300;
Aca podes utilizar un `@mixin` para que se utilice en todos los botones deshabilitados (el ejemplo esta en la linea 68/69)
Lo mismo podes hacer con focus

2022-05-09 16:21 UTC, alan199912 commented on src/scss/components/_button.scss
>  .btn-check:active+.btn-chip, .btn-check:checked+.btn-chip, .btn-chip.active, .btn-chip:active {
Se puede mejorar metiendo `:active` & `:checked` dentro de `.btn-check` de la siguiente manera:

~~~
.btn-check {
   &:active, &:checked + .btn-chip {
        // content
    }
}
~~~

2022-05-09 16:21 UTC, alan199912 commented on src/scss/components/_button.scss
> +      color: #fff;
Utilizar la variable `$white`

2022-05-10 18:21 UTC, alan199912 requested changes
2 cuestiones.
* Por que hay 2 botones con el mismo tamaño?
* Falta remover el hover cuando esta activo

2022-05-13 18:27 UTC, alan199912 requested changes
Agregar el componente en la seccion de formularios asi seguimos la misma linea que bootstrap

2022-05-13 18:27 UTC, alan199912 commented on src/scss/components/_button.scss
> +    &:hover{
No hace falta agregarle `:hover` con tal de dejar el `box-shadow` y agregarle `text-decoration: none` dentro del `&:active, &:checked` quedaria

2022-05-19 20:26 UTC, alan199912 commented on src/scss/components/_button.scss
> +    &:hover{
> No hace falta agregarle `:hover` con tal de dejar el `box-shadow` y agregarle `text-decoration: none` dentro del `&:active, &:checked` quedaria

2022-05-19 20:38 UTC, alan199912 requested changes

2022-05-19 20:38 UTC, alan199912 commented on src/scss/components/_form.scss
> +  &:active, &:checked + .btn-chip {
Lo del comentario de arriba

2022-05-20 14:18 UTC, lautarorodriguez96 commented on src/scss/components/_button.scss
> +    &:hover{
Esto lo pase al archivo _form.css porque ahora esta dentro de checkbox 
El text-decoration no lo agregué porque en el diseño está hecho que cuando está activo, se marque el subrayado

2022-05-20 21:09 UTC, alan199912 approved these changes

2022-05-26 14:58 UTC, merged