feat: Se agrega la seccion version
gcba/Obelisco pull request #82
Opened 2022-07-08 20:18 UTC by alan199912

Se agrega la seccion `Version` para que podamos visualizar la version estable.

Por cuestiones de `Storybook` no podemos poner `.` (puntos) en los nombres por ese caso se agrego `·`.

2022-07-19 15:51 UTC, alan199912 commented on src/components/Grid/Grid.stories.tsx
> +  title: 'Contenido|Grilla',
Para lo que son componentes `Contenido` separalos en otra carpeta aparte

2022-07-19 15:51 UTC, alan199912 commented on src/get_started/Get_Started.stories.tsx
> +  <div>
* Primero: no usemos `_` para separar el nombre de los componentes.
Tratemos de estandarizar todo con `camelCase`.

* Segundo : Para mejorar la lectura del documento podes agregar el estilo de `maxWidth: '75ch'` junto con el contenido centrado.

2022-07-19 20:16 UTC, alan199912 commented on src/get-started/get-started.scss
> +.get-started-container{
cambiar nombre del archivo para hacer el uso de `camelCase`, asi tambien al nombre de su carpeta

2022-07-19 20:16 UTC, alan199912 commented on src/get-started/GetStarted.stories.tsx
> +      <code>
Nos tenemos que fijar si hay alguna libraria para mostrar un poco mas lindo el codigo

2023-01-19 19:27 UTC, alan199912 commented on src/components/Nav/Nav-horizontal.stories.tsx
> +  { name: 'Link', id: '1', hasBordered: true, type: 'Grande' },
Por que cambiaste a español??

2023-01-19 19:28 UTC, alan199912 commented on .storybook/preview.ts
>          'Versión|*',
Pondria a `Version` ultimo

2023-01-19 19:42 UTC, matilope commented on src/components/Nav/Nav-horizontal.stories.tsx
> +  { name: 'Link', id: '1', hasBordered: true, type: 'Grande' },
Para poner en los ejemplos del boton el tamaño en español, cambie los size
![image](https://user-images.githubusercontent.com/66441937/213543578-47d731bc-860c-4cf9-b6fd-5c86963ba255.png)

y los cambie para que el nombre del boton diga "Chico", "Default" o "Grande".

![image](https://user-images.githubusercontent.com/66441937/213543924-7749943a-096f-4ed8-9294-c73c6f09c6ea.png)

2023-01-25 18:30 UTC, alan199912 commented on src/components/Nav/Nav-horizontal.stories.tsx
> +  { name: 'Link', id: '1', hasBordered: true, type: 'Grande' },
En este ejemplo podes hacer llave y valor, como buttonTypes con los colores

2023-01-25 18:33 UTC, alan199912 commented on src/components/Nav/Nav-horizontal.stories.tsx
> +  { name: 'Link', id: '1', hasBordered: true, type: 'Grande' },
una llave para dejar el valor en ingles, como tiene que ser, y la otra para mostrar el nombre

2023-01-25 18:33 UTC, alan199912 commented on src/components/Nav/Nav-horizontal.stories.tsx
> +  { name: 'Link', id: '1', hasBordered: true, type: 'Grande' },
```
interface SizesTypes {
  size: Size;
  name: string;
}

const sizesButton: SizesTypes[] = [
  {
    size: 'small',
    name: 'Pequeño'
  },
  {
    size: 'default',
    name: 'Mediano'
  },
  {
    size: 'large',
    name: 'Grande'
  }
];
```

2023-01-27 20:21 UTC, Jesus1397 commented on src/template/template.stories.tsx
> +      <a className="access" href="https://gcba.github.io/obelisco-demo/index.html">
Le agregaria el target="_blank" y  rel="noreferrer"> ya que versionado si lo tiene

2023-01-30 15:11 UTC, matilope commented on src/components/List-group/Vertical/VerticalAccess.stories.tsx
> +export const VerticalAccessDescription = (): JSX.Element => (
Ah si, me había olvidado de comentarte,  "Acceso horizontal con descripcion" y  "Acceso vertical con descripcion" que serian los que tienen descripcion y estan en tamaño grande se rompen

2023-01-30 15:12 UTC, matilope commented on src/components/List-group/Vertical/VerticalAccess.stories.tsx
> +export const VerticalAccessDescription = (): JSX.Element => (
Por eso queria saber si lo arreglaba de alguna forma o si hay alguna vista de esos accesos grandes con descripcion o no tienen que estar en el storybook

2023-01-30 18:40 UTC, lautarorodriguez96 commented on src/components/List-group/Vertical/VerticalAccess.stories.tsx
> +export const VerticalAccessDescription = (): JSX.Element => (
Todavia no esta resuelto si se usa o no, ni tenemos el diseño. Habria que sacarlo del storybook por el momento ese tamaño

2023-01-31 13:04 UTC, lautarorodriguez96 commented on src/get-started/GetStarted.stories.tsx
> +export const Info = (): JSX.Element => (
Como nomenclatura pondria: Comenzar - Inicio - Instalacion

2023-01-31 13:04 UTC, lautarorodriguez96 commented on src/template/template.stories.tsx
> +  title: 'Plantilla|Info'
Como nomenclatura pondría: Plantillas - Plantilla - Información

2023-01-31 14:16 UTC, matilope commented on src/components/List-group/AccessIcon.stories.tsx
>    return (
Pau y Mechi me dijeron que lo agregue el de iconos en ese tamaño también, al igual que el de descripción en tamaño grande, aunque este ultimo al final se saco, al menos por el momento.

2023-02-01 15:09 UTC, victorianastasi commented on src/get-started/GetStarted.stories.tsx
> +        <a href="CONTRIBUTING.md">contribuir de varias formas</a>.
modificar el enlace a: https://github.com/gcba/Obelisco/blob/master/CONTRIBUTING.md

2023-02-01 15:13 UTC, victorianastasi commented on src/get-started/GetStarted.stories.tsx
> +          <a href="https://asijira-confluence.buenosaires.gob.ar/display/ASI/Versiones++y+Herramientas+aceptadas+por+la+ASI">
redirige a un sitio roto, no encuentro en la web de buenos aires el sitio. encontre este https://buenosaires.gob.ar/jefaturadegabinete/agenciadesistemas/estandares sobre estandares de desarrollo ASI, pero no se si es correcto

2023-02-01 15:17 UTC, matilope commented on src/get-started/GetStarted.stories.tsx
> +          <a href="https://asijira-confluence.buenosaires.gob.ar/display/ASI/Versiones++y+Herramientas+aceptadas+por+la+ASI">
Gracias Vicky, espero confirmación de esto @lautarorodriguez96

2023-02-01 15:27 UTC, alan199912 commented on src/get-started/GetStarted.stories.tsx
> +          <a href="https://asijira-confluence.buenosaires.gob.ar/display/ASI/Versiones++y+Herramientas+aceptadas+por+la+ASI">
Funciona con la VPN

2023-02-02 13:15 UTC, lautarorodriguez96 commented on src/get-started/GetStarted.stories.tsx
> +          <a href="https://asijira-confluence.buenosaires.gob.ar/display/ASI/Versiones++y+Herramientas+aceptadas+por+la+ASI">
A mi me funciona. Igualmente va a quedar igual a lo que hoy esta en git hasta hacer el cambio de estandares

2023-02-02 13:46 UTC, davisLjr requested changes

2023-02-02 14:05 UTC, matilope commented on src/components/Nav/Nav.stories.tsx
Se cambio active -> activo y disabled -> deshabilitado. Link de momento queda igual.
Si esto cambia comenten

2023-02-02 14:06 UTC, matilope commented on src/components/Badge/Badge.stories.tsx
>    <>
De momento queda como link

2023-02-02 14:07 UTC, matilope commented on src/components/Link/Link.stories.tsx
>        </a>
Espero confirmación @lautarorodriguez96

2023-02-02 14:55 UTC, alan199912 commented on src/get-started/GetStarted.stories.tsx
> +        <span>npm</span> install @gcba/obelisco
Agregar la clase `code-box` como lo usamos en la libreria de `ngx-obelisco`

2023-02-02 14:58 UTC, alan199912 commented on src/get-started/GetStarted.stories.tsx
> +        <a href="https://gcba.github.io/estandares/componentes/web//">Ver la documentación de componentes</a>.
La url tiene un `/` de mas

2023-02-02 15:01 UTC, matilope commented on src/get-started/GetStarted.stories.tsx
> +        <a href="https://gcba.github.io/estandares/componentes/web//">Ver la documentación de componentes</a>.
deberían tener estos enlaces el target="_blank"  y el rel="noreferrer" ?

2023-02-02 15:04 UTC, alan199912 commented on src/get-started/GetStarted.stories.tsx
> +        <a href="https://gcba.github.io/estandares/componentes/web//">Ver la documentación de componentes</a>.
nope

2023-02-02 15:46 UTC, lautarorodriguez96 commented on src/components/Link/Link.stories.tsx
>        </a>
Si, yo lo dejaria como default

2023-02-02 15:48 UTC, matilope commented
Temas pendientes por resolver:
- Lorems en varios componentes: container audio, card, galeria, enlaces, nav horizontal y vertical, panel imagen y video en horizontal y vertical, tabla, tipografia.
- En botones el btn-link queda como fantasma ?
- Todo lo que diga "link" ya sea nombre de componentes, o que la palabra este presente en algun texto queda asi?
- El enlace que se llama: Default queda igual o pasa a llamarse Predeterminado?

2023-02-03 12:55 UTC, lautarorodriguez96 approved these changes

2023-02-03 13:54 UTC, alan199912 commented on src/get-started/GetStarted.stories.tsx
> +        compilado. El archivo css está ubicado en <code>/dist/obelisco.css</code> y el archivo principal de sass en{' '}
Estos estan sin la clase

2023-02-03 13:56 UTC, alan199912 commented on src/components/Audio/Audio.stories.tsx
> +/*
Por que no eliminar el codigo comentado?

2023-02-03 13:57 UTC, matilope commented on src/get-started/GetStarted.stories.tsx
> +        compilado. El archivo css está ubicado en <code>/dist/obelisco.css</code> y el archivo principal de sass en{' '}
Si, es que la clase que se usa en ngx-obelisco tiene display:flex; entonces las tira para abajo y queda feo, por eso pense en dejarla como estaba antes en estos dos casos. Ademas en si esta mostrando el path de un archivo y no es codigo

2023-02-03 13:58 UTC, matilope commented on src/components/Audio/Audio.stories.tsx
> +/*
El de noticias me dijeron que lo comente por el momento, espero confirmación ya que se apuntaba mas a eliminarlo de todas formas jaja.

2023-02-03 13:58 UTC, matilope commented on src/get-started/GetStarted.stories.tsx
> +        compilado. El archivo css está ubicado en <code>/dist/obelisco.css</code> y el archivo principal de sass en{' '}
Quizá en esos dos casos no haría falta ponerlo entre etiquetas code y se pueda usar etiqueta y alguna otra clase.

2023-02-03 14:51 UTC, victorianastasi commented on .storybook/preview-head.html
> +<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
No trae los iconos outline o round de material icons, probe con esta cdn y funciona <link href="https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp" rel="stylesheet">

2023-02-03 14:53 UTC, matilope commented on .storybook/preview-head.html
> +<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
Sisi, ahora estoy viendolo de instalarlo por npm y usar los round que son los que usan me dijo Pau. Esto lo subi asi ayer por las dudas jaja.

2023-02-03 15:47 UTC, alan199912 commented on src/get-started/GetStarted.stories.tsx
> +        compilado. El archivo css está ubicado en <code>/dist/obelisco.css</code> y el archivo principal de sass en{' '}
Bueno... en ese caso podemos crear una clase dentro (que sea hija) que tenga:
`
display: inline;
padding: 0.2rem;
`
pense en **sm** pero si encontras un buen nombre metele.
Acordate de darle una separacion a cada estilo y formatea con **Prettier**

2023-02-03 16:47 UTC, matilope commented
Bueno ahí subo funcionando el único tema es que al instalarlo por npm e intentar usar los estilos me tiraba: un error del webpack por la configuración de las reglas del "style-loader" y "css-loader".
- Lo que hice que seguramente habría que cambiar es crear en static una carpeta llamada "material-icons" y pegar el round.css ahi y luego crear otra carpeta ahí dentro llamada fonts donde estarían ambas fuentes que utiliza el round.css.
- Y luego cargar ese CSS desde el preview-head.html

* Cosas que me preocupan de esto es que al menos de esta forma, **no se si esta permitido por la licencia porque en ningún lugar figura el crédito**, excepto quizá en el get-started porque ahí aclaramos que usamos material-icons y la manera de instalarlo, etc.

* Si van a probar el material-icons un ejemplo sería:
  `<span className="material-icons-round">logout</span>`

2023-02-03 20:34 UTC, matilope commented
- Bueno al final encontré el enlace y termine agregando el CDN de material icons round, en vez de instalarlo con NPM.
- Ese CDN lo incluí en el preview-head.html
- Modifique el Get Started y el readme.md para incluir ese CDN y el NPM de material icons

2023-02-06 20:32 UTC, alan199912 reviewed
El Accesos no hay ejemplos con la clase `reverse`, salvo en el vertical.

---

En los estilos falta formatear con `Prettier`, fijate que de generar espacios para separa el codigo.
Un ejemplo:
```
.card-deck.card-column {
  .card {
    max-width: calc(calc(100% / 4) - 30px);
    @include media-breakpoint-down(md) {
      max-width: calc(calc(100% / 3) - 30px);
    }
    @include media-breakpoint-down(sm) {
      max-width: calc(calc(100% / 2) - 30px);
    }
    @include media-breakpoint-down(xs) {
      max-width: 100%;
      &:nth-of-type(2) {
        margin-top: 30px;
      }
    }
  }
}
```

2023-02-06 21:19 UTC, matilope commented
En _gallery.scss hay dos @if $images === 3

Habría que chequearlo

2023-02-07 12:53 UTC, alan199912 commented
> @if $images === 3

Quedaria la segunda, ya que el segundo bloque @if se aplica sobre el primero.
El compilador siempre tomará el último bloque @if si la condición se cumple.

2023-02-07 13:10 UTC, davisLjr approved these changes

2023-02-07 13:11 UTC, victorianastasi approved these changes

2023-02-07 13:15 UTC, Jesus1397 approved these changes

2023-02-07 13:27 UTC, merged