fix: dropdown
gcba/Obelisco pull request #99
Opened 2022-10-26 15:27 UTC by victorianastasi

2022-10-31 14:14 UTC, lautarorodriguez96 reviewed
Para que quede igual al resto, pondría como label "filtro" en vez de "desplegable"
Sumaria el tamaño faltante del dropdown

2022-10-31 19:58 UTC, alan199912 requested changes
Falta el caso de `active`

2022-11-01 13:01 UTC, lautarorodriguez96 approved these changes

2022-11-01 13:24 UTC, alan199912 approved these changes

2022-11-01 19:06 UTC, merged